CREATE EXTENSION IF NOT EXISTS pgcrypto;

WITH tiktok_sources (
  source_key,
  source_name,
  platform,
  source_type,
  source_url,
  handle,
  contact_phone,
  contact_phone_alt,
  contact_email,
  website_url,
  districts,
  listing_types,
  languages,
  hashtags,
  status,
  trust_level,
  consent_status,
  scrape_policy,
  can_contact_directly,
  notes,
  metadata
) AS (
  VALUES
    (
      'tiktok-carnelian-properties-uganda-profile',
      'TikTok profile: Carnelian Properties Uganda',
      'tiktok',
      'creator_channel',
      'https://www.tiktok.com/@carnelian.propert',
      '@carnelian.propert',
      '+256700294005',
      '+256785599477',
      'carnelianproperties4@gmail.com',
      'https://www.youtube.com/@CarnelianPropertiesuganda',
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale']::text[],
      ARRAY['English','Luganda','Kiswahili']::text[],
      ARRAY['UgandaRealEstate','KampalaRealEstate','HousesForSaleUganda','PropertyUganda']::text[],
      'active',
      'authorised_founder_contact',
      'founder_reported_agent_permission',
      'public_tiktok_profile_review_plus_authorised_agent_followup',
      TRUE,
      'TikTok source profile linked to the already-approved Carnelian source. Use the TikTok profile as a source/contact path; queue only specific 2026+ property videos/posts when source URL, price, location, and image evidence are captured.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_deep_sweep_20260524',
        'source_record_kind', 'source_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_fetch_status', 'profile_url_known_from_existing_authorised_agent_record',
        'post_payload_status', 'specific_2026_tiktok_posts_require_authenticated_tiktok_review_or_export',
        'contact_path', 'public TikTok profile plus direct authorised phone/email',
        'image_rule', 'Use TikTok public video thumbnails/stills only when attached to a specific source URL; otherwise use source evidence card and request authorised images.'
      )
    ),
    (
      'tiktok-realtor-mahad-profile',
      'TikTok profile: Realtor Mahad',
      'tiktok',
      'creator_channel',
      'https://www.tiktok.com/@realtor_mahad',
      '@realtor_mahad',
      '+256789906044',
      NULL,
      NULL,
      'https://www.youtube.com/@realtormahad',
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale','rent','land']::text[],
      ARRAY['English','Luganda','Kiswahili']::text[],
      ARRAY['RealtorMahad','KampalaRealEstate','UgandaRealEstate','TiktokUganda']::text[],
      'active',
      'review_needed',
      'public_source_review_needed',
      'public_tiktok_profile_manual_review_only',
      TRUE,
      'TikTok source profile for Realtor Mahad. A public 2023 article embeds @realtor_mahad; makaug already has the Realtor Mahad source profile. Queue only 2026+ TikTok posts with price/location/source evidence after authenticated review.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_deep_sweep_20260524',
        'source_record_kind', 'source_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://pureluxe.nl/2023/06/state-of-the-art-woning-slechts-570-000/',
        'public_fetch_status', 'profile_url_confirmed_from_public_web_reference_and_existing_makaug_source_profile',
        'post_payload_status', 'public_tiktok_web_search_returned_no_unauthenticated_2026_item_payload',
        'contact_path', 'public TikTok profile plus existing Realtor Mahad phone',
        'image_rule', 'Use TikTok public video thumbnails/stills only when attached to a specific source URL; otherwise use source evidence card and request authorised images.'
      )
    ),
    (
      'tiktok-isieh-builds-palukere-profile',
      'TikTok profile: Isieh Builds / Palukere Uganda construction source',
      'tiktok',
      'creator_channel',
      'https://www.tiktok.com/@isiehbuilds24',
      '@isiehbuilds24',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Kampala','Wakiso','Western Region']::text[],
      ARRAY['sale','land']::text[],
      ARRAY['English']::text[],
      ARRAY['HaroldHoldings','PalukereUganda','UgandaProperty','UgandaConstruction']::text[],
      'candidate',
      'source_discovery_needed',
      'public_source_review_needed',
      'public_tiktok_profile_manual_review_only',
      FALSE,
      'Construction/property-development TikTok profile discovered through public X/Twitter mirror snippets. Keep as source-review only until a specific 2026+ sale/rent/land post has price, location, and contact evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_deep_sweep_20260524',
        'source_record_kind', 'source_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://www.twstalker.com/IsiehB',
        'public_fetch_status', 'profile_url_seen_in_public_mirror_snippet',
        'post_payload_status', 'not_queued_as_property_without_specific_2026_property_listing_post',
        'contact_path', 'public TikTok profile only',
        'image_rule', 'Do not infer sale inventory from construction progress; queue only explicit property listings.'
      )
    ),
    (
      'tiktok-deep-search-uganda-property-agent-2026',
      'TikTok deep search: Uganda property agent 2026',
      'tiktok',
      'public_video_search_feed',
      'https://www.tiktok.com/search?q=Uganda%20property%20TikTok%20agent%202026',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Kampala','Wakiso','Mukono','Jinja']::text[],
      ARRAY['sale','rent','land','commercial','students']::text[],
      ARRAY['English','Luganda','Kiswahili']::text[],
      ARRAY['UgandaPropertyAgent','KampalaPropertyAgent','UgandaRealEstate','PropertyUganda']::text[],
      'candidate',
      'source_discovery_needed',
      'public_source_review_needed',
      'public_tiktok_search_manual_review_only',
      FALSE,
      'Aggressive TikTok search feed for 2026 Uganda property agents. Promote accounts/posts only after a specific public post shows source URL, price/location, contact route, and image evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_deep_sweep_20260524',
        'source_record_kind', 'discovery_feed',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_fetch_status', 'tiktok_logged_out_search_returned_app_shell_or_server_error',
        'post_payload_status', 'authenticated_tiktok_review_or_api_export_required_for_complete_item_list',
        'expected_action', 'Open in authenticated TikTok review workflow, extract specific 2026+ property posts, then import through found-online source-post importer.'
      )
    ),
    (
      'tiktok-deep-search-kampala-rentals-2026',
      'TikTok deep search: Kampala rentals 2026',
      'tiktok',
      'public_video_search_feed',
      'https://www.tiktok.com/search?q=Kampala%20rentals%202026%20TikTok',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['rent','students']::text[],
      ARRAY['English','Luganda','Kiswahili']::text[],
      ARRAY['KampalaRentals','UgandaRentals','ApartmentsForRentKampala','KampalaHostels']::text[],
      'candidate',
      'source_discovery_needed',
      'public_source_review_needed',
      'public_tiktok_search_manual_review_only',
      FALSE,
      'TikTok deep search feed for rentals and student rooms around Kampala. Do not queue generic feed rows as properties; import only specific 2026+ posts.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_deep_sweep_20260524',
        'source_record_kind', 'discovery_feed',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_fetch_status', 'tiktok_logged_out_search_returned_app_shell_or_server_error',
        'post_payload_status', 'authenticated_tiktok_review_or_api_export_required_for_complete_item_list'
      )
    ),
    (
      'tiktok-deep-search-uganda-land-2026',
      'TikTok deep search: Uganda land 2026',
      'tiktok',
      'public_video_search_feed',
      'https://www.tiktok.com/search?q=Uganda%20land%20for%20sale%202026%20TikTok',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Wakiso','Mukono','Kampala','Jinja','Mityana']::text[],
      ARRAY['land']::text[],
      ARRAY['English','Luganda','Kiswahili']::text[],
      ARRAY['LandForSaleUganda','PlotsForSaleUganda','UgandaLand','WakisoLand']::text[],
      'candidate',
      'source_discovery_needed',
      'public_source_review_needed',
      'public_tiktok_search_manual_review_only',
      FALSE,
      'TikTok deep search feed for 2026 land/plot posts. Queue only explicit posts with area, guide price, contact path, title/boundary notes, and evidence images.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_deep_sweep_20260524',
        'source_record_kind', 'discovery_feed',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_fetch_status', 'tiktok_logged_out_search_returned_app_shell_or_server_error',
        'post_payload_status', 'authenticated_tiktok_review_or_api_export_required_for_complete_item_list'
      )
    ),
    (
      'tiktok-deep-search-student-hostels-kampala-2026',
      'TikTok deep search: Kampala student hostels 2026',
      'tiktok',
      'public_video_search_feed',
      'https://www.tiktok.com/search?q=Kampala%20student%20hostel%20rooms%202026%20TikTok',
      '',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Kampala','Wakiso','Mukono']::text[],
      ARRAY['students','rent']::text[],
      ARRAY['English','Luganda','Kiswahili']::text[],
      ARRAY['StudentAccommodationUganda','KampalaHostels','MakerereHostels','KyambogoHostels']::text[],
      'candidate',
      'source_discovery_needed',
      'public_source_review_needed',
      'public_tiktok_search_manual_review_only',
      FALSE,
      'TikTok deep search feed for student accommodation and hostel posts from 2026 onward.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_deep_sweep_20260524',
        'source_record_kind', 'discovery_feed',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_fetch_status', 'tiktok_logged_out_search_returned_app_shell_or_server_error',
        'post_payload_status', 'authenticated_tiktok_review_or_api_export_required_for_complete_item_list'
      )
    )
)
INSERT INTO property_source_registry (
  source_key,
  source_name,
  platform,
  source_type,
  source_url,
  handle,
  contact_phone,
  contact_phone_alt,
  contact_email,
  website_url,
  districts,
  listing_types,
  languages,
  hashtags,
  status,
  trust_level,
  consent_status,
  scrape_policy,
  can_contact_directly,
  first_seen_at,
  last_seen_at,
  last_checked_at,
  notes,
  metadata
)
SELECT
  source_key,
  source_name,
  platform,
  source_type,
  source_url,
  handle,
  contact_phone,
  contact_phone_alt,
  contact_email,
  website_url,
  districts,
  listing_types,
  languages,
  hashtags,
  status,
  trust_level,
  consent_status,
  scrape_policy,
  can_contact_directly,
  NOW(),
  NOW(),
  NOW(),
  notes,
  metadata
FROM tiktok_sources
ON CONFLICT (source_key) DO UPDATE
SET
  source_name = EXCLUDED.source_name,
  platform = EXCLUDED.platform,
  source_type = EXCLUDED.source_type,
  source_url = EXCLUDED.source_url,
  handle = EXCLUDED.handle,
  contact_phone = COALESCE(EXCLUDED.contact_phone, property_source_registry.contact_phone),
  contact_phone_alt = COALESCE(EXCLUDED.contact_phone_alt, property_source_registry.contact_phone_alt),
  contact_email = COALESCE(EXCLUDED.contact_email, property_source_registry.contact_email),
  website_url = COALESCE(EXCLUDED.website_url, property_source_registry.website_url),
  districts = EXCLUDED.districts,
  listing_types = EXCLUDED.listing_types,
  languages = EXCLUDED.languages,
  hashtags = EXCLUDED.hashtags,
  status = EXCLUDED.status,
  trust_level = EXCLUDED.trust_level,
  consent_status = EXCLUDED.consent_status,
  scrape_policy = EXCLUDED.scrape_policy,
  can_contact_directly = EXCLUDED.can_contact_directly,
  last_seen_at = NOW(),
  last_checked_at = NOW(),
  notes = EXCLUDED.notes,
  metadata = COALESCE(property_source_registry.metadata, '{}'::jsonb) || EXCLUDED.metadata,
  updated_at = NOW();

UPDATE property_source_registry
SET
  last_checked_at = NOW(),
  metadata = COALESCE(metadata, '{}'::jsonb) || jsonb_build_object(
    'latest_platform_deep_sweep_batch', 'tiktok_deep_sweep_20260524',
    'latest_platform_deep_sweep_at', NOW(),
    'source_window_start', '2026-01-01T00:00:00.000Z',
    'platform_sweep_status', 'refreshed_for_tiktok_deep_dive',
    'logged_out_fetch_result', 'TikTok public search/tag/profile pages returned app shell, WAF challenge, or server-error state without a complete unauthenticated item list.',
    'next_ingestion_step', 'Use authenticated TikTok review/API export to extract specific 2026+ property posts, then import them with source URL, post date, location, price, contact path, and image/still URLs.'
  ),
  updated_at = NOW()
WHERE platform = 'tiktok';

UPDATE agents
SET
  verification_reason = CONCAT_WS(
    E'\n',
    NULLIF(verification_reason, ''),
    'TikTok deep sweep 20260524: public TikTok profile linked for source review: https://www.tiktok.com/@realtor_mahad'
  ),
  updated_at = NOW()
WHERE licence_number = 'SOCIAL-REALTOR-MAHAD-20260520';
