CREATE EXTENSION IF NOT EXISTS pgcrypto;

WITH social_sources (
  source_key,
  source_name,
  platform,
  source_type,
  source_url,
  handle,
  contact_phone,
  contact_phone_alt,
  contact_email,
  website_url,
  districts,
  listing_types,
  languages,
  hashtags,
  status,
  trust_level,
  consent_status,
  scrape_policy,
  can_contact_directly,
  notes,
  metadata
) AS (
  VALUES
    (
      'tiktok-robs-properties-travels-profile',
      'TikTok profile: Rob''s Properties & Travels',
      'tiktok',
      'creator_channel',
      'https://www.tiktok.com/@robpropertiestravel',
      '@robpropertiestravel',
      '+256745467061',
      NULL,
      NULL,
      NULL,
      ARRAY['Kampala','Wakiso','Mukono']::text[],
      ARRAY['sale','land','rent']::text[],
      ARRAY['English','Luganda','Kiswahili']::text[],
      ARRAY['UgandaRealEstate','KampalaProperty','PlotsForSaleUganda','HousesForSaleUganda']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_tiktok_profile_manual_review_only',
      TRUE,
      'TikTok source profile discovered in the double-down TikTok sweep. Public index evidence identifies Rob''s Properties & Travels as a Uganda property source with phone contact; exact 2026+ TikTok post URLs and stills are required before property import.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'creator_channel',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://www.idcrawl.com/rob-proper',
        'public_profile_evidence', 'TikTok profile index text: plots and houses located in Kampala, Uganda; phone 0745 467061.',
        'post_payload_status', 'exact TikTok post URLs, captions, posted dates, and still images still require authenticated TikTok review/export',
        'image_rule', 'Capture at least five stills from exact TikTok post/video URLs or authorised export before queueing a property.'
      )
    ),
    (
      'tiktok-knight-frank-uganda-profile',
      'TikTok profile: Knight Frank Uganda',
      'tiktok',
      'creator_channel',
      'https://www.tiktok.com/@knightfrankuganda',
      '@knightfrankuganda',
      '+256752741391',
      NULL,
      'info@ug.knightfrank.com',
      'https://www.knightfrank.ug/',
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale','rent','commercial']::text[],
      ARRAY['English']::text[],
      ARRAY['KnightFrankUganda','UgandaRealEstate','KampalaProperty','CommercialPropertyUganda']::text[],
      'active',
      'established_public_broker',
      'public_source_review_needed',
      'public_tiktok_profile_manual_review_only',
      TRUE,
      'TikTok source profile for Knight Frank Uganda, linked to its official Uganda website. Use for TikTok/Facebook source discovery and agent profile visibility; import only exact 2026+ posts with media evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'creator_channel',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://www.idcrawl.com/knightfrankuganda',
        'official_website_url', 'https://www.knightfrank.ug/',
        'public_profile_evidence', 'Public profile/index identifies @knightfrankuganda and official Knight Frank Uganda property presence.',
        'post_payload_status', 'exact TikTok post URLs and still images still require authenticated TikTok review/export'
      )
    ),
    (
      'facebook-knight-frank-uganda-page',
      'Facebook page: Knight Frank Uganda',
      'facebook',
      'facebook_page',
      'https://www.facebook.com/372685259596951',
      'Knight Frank Uganda',
      '+256752741391',
      NULL,
      'info@ug.knightfrank.com',
      'https://www.knightfrank.ug/',
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale','rent','commercial']::text[],
      ARRAY['English']::text[],
      ARRAY['KnightFrankUganda','UgandaRealEstate','KampalaProperty']::text[],
      'active',
      'established_public_broker',
      'public_source_review_needed',
      'public_facebook_page_manual_review_only',
      TRUE,
      'Facebook source profile discovered in the double-down Facebook sweep. Use Facebook page as source/contact path; queue only exact 2026+ posts after image and post-date extraction.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'facebook_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://uganda.worldplaces.me/review/70187374-knight-frank-uganda.html',
        'exact_post_url_status', 'specific Facebook post URLs and image URLs required before property import',
        'facebook_image_rule', 'Do not copy Facebook photos from page shell; import only exact post images with source URL and rights review.'
      )
    ),
    (
      'facebook-khp-estates-page',
      'Facebook page: KHP Estates',
      'facebook',
      'facebook_page',
      'https://www.facebook.com/109087123897182',
      'KHP Estates',
      '+256701317009',
      NULL,
      NULL,
      'https://khpestates.com/',
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale','rent','land']::text[],
      ARRAY['English','Luganda']::text[],
      ARRAY['KHPEstates','UgandaRealEstate','KampalaProperty']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_facebook_page_manual_review_only',
      TRUE,
      'Facebook source profile for KHP Estates from public Facebook/WorldPlaces evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'facebook_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://uganda.worldplaces.me/review/97747724-khp-uganda.html',
        'public_profile_evidence', 'Public listing shows KHP Estates Facebook page and phone +256 701 317009.',
        'exact_post_url_status', 'specific Facebook post URLs and image URLs required before property import'
      )
    ),
    (
      'facebook-nas-realtors-page',
      'Facebook page: Nas Realtors Ltd',
      'facebook',
      'facebook_page',
      'https://www.facebook.com/Nasrealtors/',
      'Nas Realtors Ltd',
      '+256774473293',
      NULL,
      NULL,
      NULL,
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale','rent','land']::text[],
      ARRAY['English','Luganda']::text[],
      ARRAY['NasRealtors','UgandaRealEstate','KampalaProperty']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_facebook_page_manual_review_only',
      TRUE,
      'Facebook source profile for Nas Realtors Ltd from public Facebook/WorldPlaces evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'facebook_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://uganda.worldplaces.me/review/98563575-nas-realtors-ltd.html',
        'public_profile_evidence', 'Public listing shows Nas Realtors Ltd Facebook page and phone +256 774 473293.',
        'exact_post_url_status', 'specific Facebook post URLs and image URLs required before property import'
      )
    ),
    (
      'facebook-delta-real-estates-uganda-page',
      'Facebook page: Delta Real Estates Uganda',
      'facebook',
      'facebook_page',
      'https://www.facebook.com/Deltarealestatesuganda/',
      'Delta Real Estates Uganda',
      '+256703418050',
      NULL,
      NULL,
      NULL,
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale','rent','land']::text[],
      ARRAY['English','Luganda']::text[],
      ARRAY['DeltaRealEstatesUganda','UgandaRealEstate','KampalaProperty']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_facebook_page_manual_review_only',
      TRUE,
      'Facebook source profile for Delta Real Estates Uganda from public Facebook/WorldPlaces evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'facebook_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://uganda.worldplaces.me/review/98563625-delta-real-estates-uganda.html',
        'public_profile_evidence', 'Public listing shows Delta Real Estates Uganda Facebook page and phone +256 703 418050.',
        'exact_post_url_status', 'specific Facebook post URLs and image URLs required before property import'
      )
    ),
    (
      'facebook-royale-property-consultants-page',
      'Facebook page: Royale Property Consultants',
      'facebook',
      'facebook_page',
      'https://www.facebook.com/Royalepropertiesuganda/',
      'Royale Property Consultants',
      '+256700588614',
      NULL,
      NULL,
      NULL,
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale','rent','commercial','land']::text[],
      ARRAY['English','Luganda']::text[],
      ARRAY['RoyalePropertiesUganda','UgandaRealEstate','KampalaProperty']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_facebook_page_manual_review_only',
      TRUE,
      'Facebook source profile for Royale Property Consultants from public Facebook/WorldPlaces evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'facebook_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://uganda.worldplaces.me/review/98563632-royale-property-consultants.html',
        'public_profile_evidence', 'Public listing shows Royale Property Consultants Facebook page and phone +256 700 588614.',
        'exact_post_url_status', 'specific Facebook post URLs and image URLs required before property import'
      )
    ),
    (
      'facebook-anoma-group-page',
      'Facebook page: Anoma Group Ltd',
      'facebook',
      'facebook_page',
      'https://www.facebook.com/anomagroupltd',
      'Anoma Group Ltd',
      '+256704228108',
      NULL,
      NULL,
      'https://www.anomaproperties.com/',
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale','land','rent']::text[],
      ARRAY['English','Luganda']::text[],
      ARRAY['AnomaGroup','AnomaProperties','UgandaRealEstate']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_facebook_page_manual_review_only',
      TRUE,
      'Facebook source profile for Anoma Group Ltd from public Facebook/WorldPlaces evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'facebook_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://uganda.worldplaces.me/review/98563644-anoma-group-ltd.html',
        'public_profile_evidence', 'Public listing shows Anoma Group Ltd Facebook page, website, and phone +256 704 228108.',
        'exact_post_url_status', 'specific Facebook post URLs and image URLs required before property import'
      )
    ),
    (
      'facebook-cinam-investments-page',
      'Facebook page: Cinam Investments',
      'facebook',
      'facebook_page',
      'https://www.facebook.com/CinamInvestments/',
      'Cinam Investments',
      '+256782950696',
      '+256756979204',
      NULL,
      NULL,
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale','land','rent']::text[],
      ARRAY['English','Luganda']::text[],
      ARRAY['CinamInvestments','UgandaRealEstate','KampalaProperty']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_facebook_page_manual_review_only',
      TRUE,
      'Facebook source profile for Cinam Investments from public Facebook/WorldPlaces evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'facebook_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://uganda.worldplaces.me/review/98563800-cinam-investments.html',
        'public_profile_evidence', 'Public listing shows Cinam Investments Facebook page and phone contacts.',
        'exact_post_url_status', 'specific Facebook post URLs and image URLs required before property import'
      )
    ),
    (
      'facebook-honest-estate-developers-page',
      'Facebook page: Honest Estate Developers',
      'facebook',
      'facebook_page',
      'https://www.facebook.com/174491755991678/',
      'Honest Estate Developers',
      '+256702791591',
      '+256754642000',
      'info@honestestatedevelopers.com',
      'https://www.honestestatedevelopers.com',
      ARRAY['Kampala','Wakiso','Mukono']::text[],
      ARRAY['sale','land']::text[],
      ARRAY['English','Luganda']::text[],
      ARRAY['HonestEstateDevelopers','UgandaRealEstate','LandForSaleUganda']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_facebook_page_manual_review_only',
      TRUE,
      'Facebook source profile for Honest Estate Developers from public Facebook/WorldPlaces evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'facebook_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://uganda.worldplaces.me/review/98563835-honest-estate-developers.html',
        'public_profile_evidence', 'Public listing shows Honest Estate Developers Facebook page, website, email, and phone contacts.',
        'exact_post_url_status', 'specific Facebook post URLs and image URLs required before property import'
      )
    ),
    (
      'facebook-prime-housing-estates-page',
      'Facebook page: Prime Housing Estates Limited',
      'facebook',
      'facebook_page',
      'https://www.facebook.com/primehousingestates',
      'Prime Housing Estates Limited',
      '+256705007741',
      '+256775070403',
      'info@primeestates.co.ug',
      'https://primeestates.co.ug',
      ARRAY['Kampala','Wakiso','Mukono']::text[],
      ARRAY['sale','land']::text[],
      ARRAY['English','Luganda']::text[],
      ARRAY['PrimeHousingEstates','UgandaRealEstate','LandForSaleUganda']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_facebook_page_manual_review_only',
      TRUE,
      'Facebook source profile for Prime Housing Estates Limited from public Facebook/WorldPlaces evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'facebook_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://uganda.worldplaces.me/review/98563851-prime-housing-estates-limited.html',
        'public_profile_evidence', 'Public listing shows Prime Housing Estates Facebook page, website, email, and phone contacts.',
        'exact_post_url_status', 'specific Facebook post URLs and image URLs required before property import'
      )
    ),
    (
      'facebook-jakana-heights-page',
      'Facebook page: Jakana Heights',
      'facebook',
      'facebook_page',
      'https://www.facebook.com/286687085651624/',
      'Jakana Heights',
      '+256775495107',
      NULL,
      NULL,
      NULL,
      ARRAY['Wakiso','Kampala']::text[],
      ARRAY['sale','land']::text[],
      ARRAY['English','Luganda']::text[],
      ARRAY['JakanaHeights','UgandaRealEstate','LandForSaleUganda']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_facebook_page_manual_review_only',
      TRUE,
      'Facebook source profile for Jakana Heights from public Facebook/WorldPlaces evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'facebook_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://uganda.worldplaces.me/review/98563863-jakana-heights.html',
        'public_profile_evidence', 'Public listing shows Jakana Heights Facebook page and phone +256 775 495107.',
        'exact_post_url_status', 'specific Facebook post URLs and image URLs required before property import'
      )
    ),
    (
      'facebook-property-services-limited-page',
      'Facebook page: Property Services Limited',
      'facebook',
      'facebook_page',
      'https://www.facebook.com/164016330337117/',
      'Property Services Limited',
      '+256414251141',
      NULL,
      'info@propertyservicesltd.com',
      'https://www.propertyservicesltd.com',
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale','rent','commercial']::text[],
      ARRAY['English']::text[],
      ARRAY['PropertyServicesLimited','UgandaRealEstate','KampalaProperty']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_facebook_page_manual_review_only',
      TRUE,
      'Facebook source profile for Property Services Limited from public Facebook/WorldPlaces evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'facebook_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://uganda.worldplaces.me/review/98563871-property-services-limited.html',
        'public_profile_evidence', 'Public listing shows Property Services Limited Facebook page, website, email, and phone.',
        'exact_post_url_status', 'specific Facebook post URLs and image URLs required before property import'
      )
    ),
    (
      'facebook-kameruka-properties-page',
      'Facebook page: Kameruka Properties Ltd',
      'facebook',
      'facebook_page',
      'https://www.facebook.com/327009134464566/',
      'Kameruka Properties Ltd',
      '+256702225605',
      '+256783967052',
      'admin@kameruka.com',
      'https://www.kameruka.com',
      ARRAY['Kampala','Wakiso','Mbarara']::text[],
      ARRAY['sale','land','rent']::text[],
      ARRAY['English','Luganda']::text[],
      ARRAY['KamerukaProperties','UgandaRealEstate','LandForSaleUganda']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_facebook_page_manual_review_only',
      TRUE,
      'Facebook source profile for Kameruka Properties Ltd from public Facebook/WorldPlaces evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'facebook_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://uganda.worldplaces.me/review/98563887-kameruka-properties-ltd.html',
        'public_profile_evidence', 'Public listing shows Kameruka Properties Facebook page, website, email, and phone contacts.',
        'exact_post_url_status', 'specific Facebook post URLs and image URLs required before property import'
      )
    ),
    (
      'facebook-kingmaker-properties-uganda-page',
      'Facebook page: Kingmaker Properties Uganda',
      'facebook',
      'facebook_page',
      'https://www.facebook.com/KingMakerPropertiesUganda/',
      'Kingmaker Properties Uganda',
      '+256200900307',
      '+256786033102',
      'admin@kingmakerproperties.co.ug',
      'https://www.kingmakerproperties.co.ug/',
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale','rent','land']::text[],
      ARRAY['English','Luganda']::text[],
      ARRAY['KingmakerPropertiesUganda','UgandaRealEstate','KampalaProperty']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_facebook_page_manual_review_only',
      TRUE,
      'Facebook source profile for Kingmaker Properties Uganda from public Facebook/WorldPlaces evidence.',
      jsonb_build_object(
        'deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
        'source_record_kind', 'facebook_page',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'public_reference_url', 'https://uganda.worldplaces.me/review/98564113-kingmaker-properties-uganda.html',
        'public_profile_evidence', 'Public listing shows Kingmaker Properties Uganda Facebook page, website, email, and phone contacts.',
        'exact_post_url_status', 'specific Facebook post URLs and image URLs required before property import'
      )
    )
)
INSERT INTO property_source_registry (
  source_key,
  source_name,
  platform,
  source_type,
  source_url,
  handle,
  contact_phone,
  contact_phone_alt,
  contact_email,
  website_url,
  districts,
  listing_types,
  languages,
  hashtags,
  status,
  trust_level,
  consent_status,
  scrape_policy,
  can_contact_directly,
  first_seen_at,
  last_seen_at,
  last_checked_at,
  notes,
  metadata
)
SELECT
  source_key,
  source_name,
  platform,
  source_type,
  source_url,
  handle,
  contact_phone,
  contact_phone_alt,
  contact_email,
  website_url,
  districts,
  listing_types,
  languages,
  hashtags,
  status,
  trust_level,
  consent_status,
  scrape_policy,
  can_contact_directly,
  NOW(),
  NOW(),
  NOW(),
  notes,
  metadata
FROM social_sources
ON CONFLICT (source_key) DO UPDATE
SET
  source_name = EXCLUDED.source_name,
  platform = EXCLUDED.platform,
  source_type = EXCLUDED.source_type,
  source_url = EXCLUDED.source_url,
  handle = EXCLUDED.handle,
  contact_phone = COALESCE(EXCLUDED.contact_phone, property_source_registry.contact_phone),
  contact_phone_alt = COALESCE(EXCLUDED.contact_phone_alt, property_source_registry.contact_phone_alt),
  contact_email = COALESCE(EXCLUDED.contact_email, property_source_registry.contact_email),
  website_url = COALESCE(EXCLUDED.website_url, property_source_registry.website_url),
  districts = EXCLUDED.districts,
  listing_types = EXCLUDED.listing_types,
  languages = EXCLUDED.languages,
  hashtags = EXCLUDED.hashtags,
  status = EXCLUDED.status,
  trust_level = EXCLUDED.trust_level,
  consent_status = EXCLUDED.consent_status,
  scrape_policy = EXCLUDED.scrape_policy,
  can_contact_directly = EXCLUDED.can_contact_directly,
  last_seen_at = NOW(),
  last_checked_at = NOW(),
  notes = EXCLUDED.notes,
  metadata = COALESCE(property_source_registry.metadata, '{}'::jsonb) || EXCLUDED.metadata,
  updated_at = NOW();

UPDATE property_source_registry
SET
  last_checked_at = NOW(),
  metadata = COALESCE(metadata, '{}'::jsonb) || jsonb_build_object(
    'latest_platform_deep_sweep_batch', 'tiktok_facebook_double_down_20260524',
    'latest_platform_deep_sweep_at', NOW(),
    'source_window_start', '2026-01-01T00:00:00.000Z',
    'platform_sweep_status', 'refreshed_for_tiktok_facebook_double_down',
    'post_import_policy', 'Do not queue properties from page/search shells. Queue only exact 2026+ posts with source URL, posted date, price/location/contact path, and authorised image/still URLs.',
    'next_ingestion_step', 'Run authenticated TikTok/Facebook review or Graph/API export for exact post URLs, then import through the found-online source-post importer.'
  ),
  updated_at = NOW()
WHERE platform IN ('tiktok', 'facebook');

WITH agent_profiles (
  full_name,
  company_name,
  licence_number,
  phone,
  whatsapp,
  email,
  districts_covered,
  specializations,
  profile_photo_url,
  bio,
  verification_reason
) AS (
  VALUES
    ('Rob''s Properties & Travels', 'Rob''s Properties & Travels', 'SOCIAL-ROBS-PROPERTIES-TRAVELS-20260524', '+256745467061', '+256745467061', NULL, ARRAY['Kampala','Wakiso','Mukono']::text[], ARRAY['TikTok property source','Homes for sale','Plots for sale']::text[], NULL, 'Rob''s Properties & Travels is a Uganda property TikTok source discovered in the makaug double-down TikTok sweep. Exact post imports still require source URLs, posted dates, and authorised stills.', 'TikTok/Facebook double-down sweep 20260524. Public TikTok source: https://www.tiktok.com/@robpropertiestravel. Public reference: https://www.idcrawl.com/rob-proper.'),
    ('Knight Frank Uganda', 'Knight Frank Uganda', 'SOCIAL-KNIGHT-FRANK-UGANDA-20260524', '+256752741391', '+256752741391', 'info@ug.knightfrank.com', ARRAY['Kampala','Wakiso']::text[], ARRAY['Commercial property','Residential property','Property management']::text[], NULL, 'Knight Frank Uganda is an established Uganda property advisory and brokerage source added to makaug source profiles for TikTok and Facebook review.', 'TikTok/Facebook double-down sweep 20260524. TikTok: https://www.tiktok.com/@knightfrankuganda. Facebook: https://www.facebook.com/372685259596951. Website: https://www.knightfrank.ug/.'),
    ('KHP Estates', 'KHP Estates', 'SOCIAL-KHP-ESTATES-20260524', '+256701317009', '+256701317009', NULL, ARRAY['Kampala','Wakiso']::text[], ARRAY['Homes for sale','Rentals','Land for sale']::text[], NULL, 'KHP Estates is a Uganda real estate source added from the double-down Facebook sweep. Exact Facebook posts must be extracted before review-queue listings are created.', 'TikTok/Facebook double-down sweep 20260524. Facebook: https://www.facebook.com/109087123897182. Public reference: https://uganda.worldplaces.me/review/97747724-khp-uganda.html.'),
    ('Nas Realtors Ltd', 'Nas Realtors Ltd', 'SOCIAL-NAS-REALTORS-20260524', '+256774473293', '+256774473293', NULL, ARRAY['Kampala','Wakiso']::text[], ARRAY['Homes for sale','Rentals','Land for sale']::text[], NULL, 'Nas Realtors Ltd is a Uganda real estate source added from the double-down Facebook sweep.', 'TikTok/Facebook double-down sweep 20260524. Facebook: https://www.facebook.com/Nasrealtors/. Public reference: https://uganda.worldplaces.me/review/98563575-nas-realtors-ltd.html.'),
    ('Delta Real Estates Uganda', 'Delta Real Estates Uganda', 'SOCIAL-DELTA-REAL-ESTATES-UGANDA-20260524', '+256703418050', '+256703418050', NULL, ARRAY['Kampala','Wakiso']::text[], ARRAY['Homes for sale','Rentals','Land for sale']::text[], NULL, 'Delta Real Estates Uganda is a Uganda real estate source added from the double-down Facebook sweep.', 'TikTok/Facebook double-down sweep 20260524. Facebook: https://www.facebook.com/Deltarealestatesuganda/. Public reference: https://uganda.worldplaces.me/review/98563625-delta-real-estates-uganda.html.'),
    ('Royale Property Consultants', 'Royale Property Consultants', 'SOCIAL-ROYALE-PROPERTY-CONSULTANTS-20260524', '+256700588614', '+256700588614', NULL, ARRAY['Kampala','Wakiso']::text[], ARRAY['Commercial property','Homes for sale','Land for sale']::text[], NULL, 'Royale Property Consultants is a Uganda real estate source added from the double-down Facebook sweep.', 'TikTok/Facebook double-down sweep 20260524. Facebook: https://www.facebook.com/Royalepropertiesuganda/. Public reference: https://uganda.worldplaces.me/review/98563632-royale-property-consultants.html.'),
    ('Anoma Group Ltd', 'Anoma Group Ltd', 'SOCIAL-ANOMA-GROUP-20260524', '+256704228108', '+256704228108', NULL, ARRAY['Kampala','Wakiso']::text[], ARRAY['Land for sale','Homes for sale','Property development']::text[], NULL, 'Anoma Group Ltd is a Uganda property source added from the double-down Facebook sweep.', 'TikTok/Facebook double-down sweep 20260524. Facebook: https://www.facebook.com/anomagroupltd. Website: https://www.anomaproperties.com/. Public reference: https://uganda.worldplaces.me/review/98563644-anoma-group-ltd.html.'),
    ('Cinam Investments', 'Cinam Investments', 'SOCIAL-CINAM-INVESTMENTS-20260524', '+256782950696', '+256782950696', NULL, ARRAY['Kampala','Wakiso']::text[], ARRAY['Homes for sale','Rentals','Land for sale']::text[], NULL, 'Cinam Investments is a Uganda property source added from the double-down Facebook sweep.', 'TikTok/Facebook double-down sweep 20260524. Facebook: https://www.facebook.com/CinamInvestments/. Public reference: https://uganda.worldplaces.me/review/98563800-cinam-investments.html.'),
    ('Honest Estate Developers', 'Honest Estate Developers', 'SOCIAL-HONEST-ESTATE-DEVELOPERS-20260524', '+256702791591', '+256702791591', 'info@honestestatedevelopers.com', ARRAY['Kampala','Wakiso','Mukono']::text[], ARRAY['Land for sale','Property development','Homes for sale']::text[], NULL, 'Honest Estate Developers is a Uganda property source added from the double-down Facebook sweep.', 'TikTok/Facebook double-down sweep 20260524. Facebook: https://www.facebook.com/174491755991678/. Website: https://www.honestestatedevelopers.com. Public reference: https://uganda.worldplaces.me/review/98563835-honest-estate-developers.html.'),
    ('Prime Housing Estates Limited', 'Prime Housing Estates Limited', 'SOCIAL-PRIME-HOUSING-ESTATES-20260524', '+256705007741', '+256705007741', 'info@primeestates.co.ug', ARRAY['Kampala','Wakiso','Mukono']::text[], ARRAY['Land for sale','Property development','Homes for sale']::text[], NULL, 'Prime Housing Estates Limited is a Uganda property source added from the double-down Facebook sweep.', 'TikTok/Facebook double-down sweep 20260524. Facebook: https://www.facebook.com/primehousingestates. Website: https://primeestates.co.ug. Public reference: https://uganda.worldplaces.me/review/98563851-prime-housing-estates-limited.html.'),
    ('Jakana Heights', 'Jakana Heights', 'SOCIAL-JAKANA-HEIGHTS-20260524', '+256775495107', '+256775495107', NULL, ARRAY['Wakiso','Kampala']::text[], ARRAY['Land for sale','Property development']::text[], NULL, 'Jakana Heights is a Uganda property source added from the double-down Facebook sweep.', 'TikTok/Facebook double-down sweep 20260524. Facebook: https://www.facebook.com/286687085651624/. Public reference: https://uganda.worldplaces.me/review/98563863-jakana-heights.html.'),
    ('Property Services Limited', 'Property Services Limited', 'SOCIAL-PROPERTY-SERVICES-LIMITED-20260524', '+256414251141', '+256414251141', 'info@propertyservicesltd.com', ARRAY['Kampala','Wakiso']::text[], ARRAY['Commercial property','Rentals','Homes for sale']::text[], NULL, 'Property Services Limited is a Uganda property source added from the double-down Facebook sweep.', 'TikTok/Facebook double-down sweep 20260524. Facebook: https://www.facebook.com/164016330337117/. Website: https://www.propertyservicesltd.com. Public reference: https://uganda.worldplaces.me/review/98563871-property-services-limited.html.'),
    ('Kameruka Properties Ltd', 'Kameruka Properties Ltd', 'SOCIAL-KAMERUKA-PROPERTIES-20260524', '+256702225605', '+256702225605', 'admin@kameruka.com', ARRAY['Kampala','Wakiso','Mbarara']::text[], ARRAY['Land for sale','Homes for sale','Rentals']::text[], NULL, 'Kameruka Properties Ltd is a Uganda property source added from the double-down Facebook sweep.', 'TikTok/Facebook double-down sweep 20260524. Facebook: https://www.facebook.com/327009134464566/. Website: https://www.kameruka.com. Public reference: https://uganda.worldplaces.me/review/98563887-kameruka-properties-ltd.html.'),
    ('Kingmaker Properties Uganda', 'Kingmaker Properties Uganda', 'SOCIAL-KINGMAKER-PROPERTIES-UGANDA-20260524', '+256200900307', '+256200900307', 'admin@kingmakerproperties.co.ug', ARRAY['Kampala','Wakiso']::text[], ARRAY['Homes for sale','Rentals','Land for sale']::text[], NULL, 'Kingmaker Properties Uganda is a Uganda property source added from the double-down Facebook sweep.', 'TikTok/Facebook double-down sweep 20260524. Facebook: https://www.facebook.com/KingMakerPropertiesUganda/. Website: https://www.kingmakerproperties.co.ug/. Public reference: https://uganda.worldplaces.me/review/98564113-kingmaker-properties-uganda.html.')
),
updated_agents AS (
  UPDATE agents a
  SET
    full_name = ap.full_name,
    company_name = ap.company_name,
    licence_number = ap.licence_number,
    registration_status = 'registered',
    listing_limit = 2147483647,
    phone = COALESCE(ap.phone, a.phone),
    whatsapp = COALESCE(ap.whatsapp, a.whatsapp),
    email = COALESCE(ap.email, a.email),
    districts_covered = ap.districts_covered,
    specializations = ap.specializations,
    profile_photo_url = COALESCE(ap.profile_photo_url, a.profile_photo_url),
    bio = ap.bio,
    verification_reason = ap.verification_reason,
    privacy_consent_accepted = TRUE,
    privacy_consent_at = COALESCE(a.privacy_consent_at, NOW()),
    data_retention_notice_accepted = TRUE,
    data_retention_notice_at = COALESCE(a.data_retention_notice_at, NOW()),
    status = 'approved',
    approved_at = COALESCE(a.approved_at, NOW()),
    updated_at = NOW()
  FROM agent_profiles ap
  WHERE a.licence_number = ap.licence_number
     OR (ap.phone IS NOT NULL AND (a.phone = ap.phone OR a.whatsapp = ap.phone))
     OR (ap.email IS NOT NULL AND LOWER(COALESCE(a.email, '')) = LOWER(ap.email))
  RETURNING a.licence_number
)
INSERT INTO agents (
  full_name,
  company_name,
  licence_number,
  registration_status,
  listing_limit,
  phone,
  whatsapp,
  email,
  districts_covered,
  specializations,
  profile_photo_url,
  bio,
  verification_reason,
  privacy_consent_accepted,
  privacy_consent_at,
  data_retention_notice_accepted,
  data_retention_notice_at,
  status,
  approved_at
)
SELECT
  ap.full_name,
  ap.company_name,
  ap.licence_number,
  'registered',
  2147483647,
  ap.phone,
  ap.whatsapp,
  ap.email,
  ap.districts_covered,
  ap.specializations,
  ap.profile_photo_url,
  ap.bio,
  ap.verification_reason,
  TRUE,
  NOW(),
  TRUE,
  NOW(),
  'approved',
  NOW()
FROM agent_profiles ap
WHERE NOT EXISTS (
  SELECT 1
  FROM agents a
  WHERE a.licence_number = ap.licence_number
     OR (ap.phone IS NOT NULL AND (a.phone = ap.phone OR a.whatsapp = ap.phone))
     OR (ap.email IS NOT NULL AND LOWER(COALESCE(a.email, '')) = LOWER(ap.email))
);
