CREATE EXTENSION IF NOT EXISTS pgcrypto;

WITH x_sources (
  source_key,
  source_name,
  platform,
  source_type,
  source_url,
  handle,
  contact_phone,
  contact_phone_alt,
  contact_email,
  website_url,
  districts,
  listing_types,
  languages,
  hashtags,
  status,
  trust_level,
  consent_status,
  scrape_policy,
  can_contact_directly,
  notes,
  metadata
) AS (
  VALUES
    (
      'x-knight-frank-uganda-profile',
      'X profile: Knight Frank Uganda',
      'x',
      'creator_channel',
      'https://x.com/knightfrankug',
      '@knightfrankug',
      '+256752741391',
      NULL,
      'info@ug.knightfrank.com',
      'https://www.knightfrank.ug/',
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale','rent','commercial']::text[],
      ARRAY['English']::text[],
      ARRAY['KnightFrankUganda','UgandaRealEstate','KampalaProperty','CommercialPropertyUganda']::text[],
      'active',
      'established_public_broker',
      'public_source_review_needed',
      'public_x_profile_manual_review_only',
      TRUE,
      'Named X/Twitter source profile for Knight Frank Uganda. Public X profile and index evidence show recurring Uganda property commentary and listings; exact 2026+ post URL, posted date, media, price/location/contact path are still required before property import.',
      jsonb_build_object(
        'social_first_priority_batch', 'social_first_x_priority_20260524',
        'source_record_kind', 'creator_channel',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'platform_priority_tier', 'priority_social_channel',
        'profile_creation_rule', 'Create or update a makaug source/broker profile only when the source shows repeated property activity, plural inventory, or cross-platform presence. A single isolated property post stays as a found-online listing without a profile.',
        'single_listing_rule', 'One-off public X posts can become found-online listings when evidence is complete, but do not create a profile until repeated inventory or multi-platform presence is observed.',
        'image_rights_rule', 'Use exact public post media, thumbnails, or authorised screenshots/stills only with source URL and reviewer rights check; do not copy private or untraceable images.',
        'public_reference_url', 'https://mobile.twstalker.com/knightfrankug',
        'public_profile_evidence', 'Public profile index shows @knightfrankug, Kampala/Uganda location, official website, thousands of posts/followers, and recent property-related posts.',
        'post_payload_status', 'exact X/Twitter post URLs, posted dates, image URLs, and stills required before review-queue property import'
      )
    ),
    (
      'x-broll-uganda-profile',
      'X profile: Broll Uganda',
      'x',
      'creator_channel',
      'https://x.com/BrollUganda',
      '@BrollUganda',
      NULL,
      NULL,
      NULL,
      'https://broll.ug/',
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale','rent','commercial']::text[],
      ARRAY['English']::text[],
      ARRAY['BrollUganda','UgandaRealEstate','KampalaProperty','CommercialPropertyUganda']::text[],
      'active',
      'established_public_broker',
      'public_source_review_needed',
      'public_x_profile_manual_review_only',
      TRUE,
      'Named X/Twitter source profile for Broll Uganda. Public X profile evidence shows recurring Uganda property market activity and a dedicated website; queue exact posts only after post-date and media extraction.',
      jsonb_build_object(
        'social_first_priority_batch', 'social_first_x_priority_20260524',
        'source_record_kind', 'creator_channel',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'platform_priority_tier', 'priority_social_channel',
        'profile_creation_rule', 'Create or update a makaug source/broker profile only when the source shows repeated property activity, plural inventory, or cross-platform presence. A single isolated property post stays as a found-online listing without a profile.',
        'single_listing_rule', 'One-off public X posts can become found-online listings when evidence is complete, but do not create a profile until repeated inventory or multi-platform presence is observed.',
        'image_rights_rule', 'Use exact public post media, thumbnails, or authorised screenshots/stills only with source URL and reviewer rights check; do not copy private or untraceable images.',
        'public_reference_url', 'https://twitter.com/BrollUganda/with_replies',
        'public_profile_evidence', 'Public X profile states Broll Uganda is reimagining real estate services in Uganda, links to broll.ug, and has recurring posts/follower activity.',
        'post_payload_status', 'exact X/Twitter post URLs, posted dates, image URLs, and stills required before review-queue property import'
      )
    ),
    (
      'x-chris-property-uganda-profile',
      'X profile: Chris Property Uganda Ltd',
      'x',
      'creator_channel',
      'https://x.com/chrispropertyug',
      '@chrispropertyug',
      '+256756917480',
      '+256784758762',
      NULL,
      'https://chrispropertyuganda.com/',
      ARRAY['Kampala','Wakiso','Mukono','Entebbe']::text[],
      ARRAY['sale','rent','land']::text[],
      ARRAY['English','Luganda']::text[],
      ARRAY['ChrisPropertyUganda','UgandaRealEstate','PlotsForSaleUganda','HousesForSaleUganda']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_x_profile_manual_review_only',
      TRUE,
      'Named X/Twitter source profile for Chris Property Uganda Ltd. Public profile/index evidence shows repeated plot and house sale posts with phone contact; exact post URLs and images are required before property import.',
      jsonb_build_object(
        'social_first_priority_batch', 'social_first_x_priority_20260524',
        'source_record_kind', 'creator_channel',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'platform_priority_tier', 'priority_social_channel',
        'profile_creation_rule', 'Create or update a makaug source/broker profile only when the source shows repeated property activity, plural inventory, or cross-platform presence. A single isolated property post stays as a found-online listing without a profile.',
        'single_listing_rule', 'One-off public X posts can become found-online listings when evidence is complete, but do not create a profile until repeated inventory or multi-platform presence is observed.',
        'image_rights_rule', 'Use exact public post media, thumbnails, or authorised screenshots/stills only with source URL and reviewer rights check; do not copy private or untraceable images.',
        'public_reference_url', 'https://mobile.twstalker.com/chrispropertyug',
        'public_profile_evidence', 'Public profile index describes sale of land, houses and apartments across Kampala/Greater Kampala and shows recent repeated plot/house posts.',
        'post_payload_status', 'exact X/Twitter post URLs, posted dates, image URLs, and stills required before review-queue property import'
      )
    ),
    (
      'x-ecoland-property-services-profile',
      'X profile: Ecoland Property Services',
      'x',
      'creator_channel',
      'https://x.com/ecolandproperty',
      '@ecolandproperty',
      '+256755700700',
      '+256772381544',
      'info@ecolandproperty.com',
      'https://www.ecolandproperty.com/',
      ARRAY['Kampala','Wakiso','Mukono','Entebbe','Luwero']::text[],
      ARRAY['sale','rent','land','commercial']::text[],
      ARRAY['English','Luganda']::text[],
      ARRAY['EcolandProperty','UgandaRealEstate','KampalaProperty','LandForSaleUganda']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_x_profile_manual_review_only',
      TRUE,
      'Named X/Twitter source profile for Ecoland Property Services. Public X and website evidence show repeated sale/rent inventory; exact X post URLs and media remain required before property import.',
      jsonb_build_object(
        'social_first_priority_batch', 'social_first_x_priority_20260524',
        'source_record_kind', 'creator_channel',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'platform_priority_tier', 'priority_social_channel',
        'profile_creation_rule', 'Create or update a makaug source/broker profile only when the source shows repeated property activity, plural inventory, or cross-platform presence. A single isolated property post stays as a found-online listing without a profile.',
        'single_listing_rule', 'One-off public X posts can become found-online listings when evidence is complete, but do not create a profile until repeated inventory or multi-platform presence is observed.',
        'image_rights_rule', 'Use exact public post media, thumbnails, or authorised screenshots/stills only with source URL and reviewer rights check; do not copy private or untraceable images.',
        'public_reference_url', 'https://twitter.com/ecolandproperty/with_replies',
        'website_reference_url', 'https://www.ecolandproperty.com/author/contentadmin/',
        'public_profile_evidence', 'Public profile/search evidence describes Ecoland Property Services as a Uganda real-estate company specialising in property for sale and rent, and its site shows many property records.',
        'post_payload_status', 'exact X/Twitter post URLs, posted dates, image URLs, and stills required before review-queue property import'
      )
    ),
    (
      'x-bigways-ug-profile',
      'X profile: Bigways',
      'x',
      'creator_channel',
      'https://x.com/Bigways_UG',
      '@Bigways_UG',
      '+256703200619',
      NULL,
      NULL,
      'https://bigways.co.ug/',
      ARRAY['Kampala','Wakiso']::text[],
      ARRAY['sale','rent','land']::text[],
      ARRAY['English','Luganda']::text[],
      ARRAY['BigwaysUG','UgandaRealEstate','KampalaProperty','LandForSaleUganda']::text[],
      'candidate',
      'review_needed',
      'public_source_review_needed',
      'public_x_profile_manual_review_only',
      TRUE,
      'Named X/Twitter source profile for Bigways. Public X evidence describes real-estate deals and plural buy/sell activity in Kampala/Wakiso with a phone contact and Facebook-page reference.',
      jsonb_build_object(
        'social_first_priority_batch', 'social_first_x_priority_20260524',
        'source_record_kind', 'creator_channel',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'platform_priority_tier', 'priority_social_channel',
        'profile_creation_rule', 'Create or update a makaug source/broker profile only when the source shows repeated property activity, plural inventory, or cross-platform presence. A single isolated property post stays as a found-online listing without a profile.',
        'single_listing_rule', 'One-off public X posts can become found-online listings when evidence is complete, but do not create a profile until repeated inventory or multi-platform presence is observed.',
        'image_rights_rule', 'Use exact public post media, thumbnails, or authorised screenshots/stills only with source URL and reviewer rights check; do not copy private or untraceable images.',
        'public_reference_url', 'https://twitter.com/Bigways_UG/with_replies',
        'public_profile_evidence', 'Public X profile says REAL ESTATE DEALS, buy and sell properties in Kampala and Wakiso, with phone contact and Facebook-page reference.',
        'post_payload_status', 'exact X/Twitter post URLs, posted dates, image URLs, and stills required before review-queue property import'
      )
    ),
    (
      'x-architecture-interior-uganda-profile',
      'X profile: Architecture & Interior Uganda',
      'x',
      'creator_channel',
      'https://x.com/arc_Ug_',
      '@arc_Ug_',
      NULL,
      NULL,
      NULL,
      NULL,
      ARRAY['Kampala']::text[],
      ARRAY['sale','rent','commercial']::text[],
      ARRAY['English']::text[],
      ARRAY['ArchitectureUganda','UgandaRealEstate','KampalaProperty']::text[],
      'candidate',
      'source_discovery_needed',
      'public_source_review_needed',
      'public_x_profile_manual_review_only',
      FALSE,
      'Candidate X/Twitter source profile. It is tracked for discovery only until repeated property inventory or cross-platform presence is confirmed; no makaug broker profile is created from this single-profile evidence.',
      jsonb_build_object(
        'social_first_priority_batch', 'social_first_x_priority_20260524',
        'source_record_kind', 'creator_channel',
        'review_required', true,
        'source_window_start', '2026-01-01T00:00:00.000Z',
        'platform_priority_tier', 'priority_social_channel',
        'profile_creation_rule', 'Create or update a makaug source/broker profile only when the source shows repeated property activity, plural inventory, or cross-platform presence. A single isolated property post stays as a found-online listing without a profile.',
        'single_listing_rule', 'One-off public X posts can become found-online listings when evidence is complete, but do not create a profile until repeated inventory or multi-platform presence is observed.',
        'profile_creation_status', 'blocked_until_repeated_inventory_or_cross_platform_presence',
        'image_rights_rule', 'Use exact public post media, thumbnails, or authorised screenshots/stills only with source URL and reviewer rights check; do not copy private or untraceable images.',
        'public_reference_url', 'https://twitter.com/arc_Ug_',
        'public_profile_evidence', 'Public X profile only identifies Real Estate in Kampala. Track as source discovery; do not create a broker profile yet.',
        'post_payload_status', 'exact X/Twitter post URLs, posted dates, image URLs, and stills required before review-queue property import'
      )
    )
)
INSERT INTO property_source_registry (
  source_key,
  source_name,
  platform,
  source_type,
  source_url,
  handle,
  contact_phone,
  contact_phone_alt,
  contact_email,
  website_url,
  districts,
  listing_types,
  languages,
  hashtags,
  status,
  trust_level,
  consent_status,
  scrape_policy,
  can_contact_directly,
  first_seen_at,
  last_seen_at,
  last_checked_at,
  notes,
  metadata
)
SELECT
  source_key,
  source_name,
  platform,
  source_type,
  source_url,
  handle,
  contact_phone,
  contact_phone_alt,
  contact_email,
  website_url,
  districts,
  listing_types,
  languages,
  hashtags,
  status,
  trust_level,
  consent_status,
  scrape_policy,
  can_contact_directly,
  NOW(),
  NOW(),
  NOW(),
  notes,
  metadata
FROM x_sources
ON CONFLICT (source_key) DO UPDATE
SET
  source_name = EXCLUDED.source_name,
  platform = EXCLUDED.platform,
  source_type = EXCLUDED.source_type,
  source_url = EXCLUDED.source_url,
  handle = EXCLUDED.handle,
  contact_phone = COALESCE(EXCLUDED.contact_phone, property_source_registry.contact_phone),
  contact_phone_alt = COALESCE(EXCLUDED.contact_phone_alt, property_source_registry.contact_phone_alt),
  contact_email = COALESCE(EXCLUDED.contact_email, property_source_registry.contact_email),
  website_url = COALESCE(EXCLUDED.website_url, property_source_registry.website_url),
  districts = EXCLUDED.districts,
  listing_types = EXCLUDED.listing_types,
  languages = EXCLUDED.languages,
  hashtags = EXCLUDED.hashtags,
  status = EXCLUDED.status,
  trust_level = EXCLUDED.trust_level,
  consent_status = EXCLUDED.consent_status,
  scrape_policy = EXCLUDED.scrape_policy,
  can_contact_directly = EXCLUDED.can_contact_directly,
  last_seen_at = NOW(),
  last_checked_at = NOW(),
  notes = EXCLUDED.notes,
  metadata = COALESCE(property_source_registry.metadata, '{}'::jsonb) || EXCLUDED.metadata,
  updated_at = NOW();

UPDATE property_source_registry
SET
  last_checked_at = NOW(),
  metadata = COALESCE(metadata, '{}'::jsonb) || jsonb_build_object(
    'social_first_priority_batch', 'social_first_x_priority_20260524',
    'latest_social_first_sweep_at', NOW(),
    'source_window_start', '2026-01-01T00:00:00.000Z',
    'platform_priority_tier', CASE
      WHEN platform IN ('tiktok', 'facebook', 'youtube', 'x', 'instagram') THEN 'priority_social_channel'
      ELSE 'secondary_website_or_portal'
    END,
    'profile_creation_rule', 'Create or update a makaug source/broker profile only when the source shows repeated property activity, plural inventory, or cross-platform presence. A single isolated property post stays as a found-online listing without a profile.',
    'single_listing_rule', 'One-off social posts can become found-online listings when evidence is complete, but do not create a profile until repeated inventory or multi-platform presence is observed.',
    'post_import_policy', 'Queue only exact 2026+ property posts/listings with source URL, first-posted date, price or guide price, location, contact path, and usable images/stills. Do not fabricate from account shells or search pages.',
    'image_rights_rule', 'Use exact public post media, thumbnails, authorised screenshots, YouTube/TikTok stills, or a labelled makaug evidence card with source URL and reviewer rights check.',
    'next_ingestion_step', 'Prioritise TikTok, Facebook, YouTube, X/Twitter, then Instagram; use websites only as secondary confirmation or repeat-inventory evidence.'
  ),
  updated_at = NOW()
WHERE platform IN ('tiktok', 'facebook', 'youtube', 'x', 'instagram', 'website');

WITH agent_profiles (
  full_name,
  company_name,
  licence_number,
  phone,
  whatsapp,
  email,
  districts_covered,
  specializations,
  profile_photo_url,
  bio,
  verification_reason
) AS (
  VALUES
    ('Broll Uganda', 'Broll Uganda', 'SOCIAL-BROLL-UGANDA-X-20260524', NULL, NULL, NULL, ARRAY['Kampala','Wakiso']::text[], ARRAY['X/Twitter property source','Commercial property','Residential property','Property market research']::text[], NULL, 'Broll Uganda is a recurring Uganda property source added from the social-first X/Twitter sweep. Exact post imports still require source URLs, first-posted dates, and authorised images/stills.', 'Social-first X/Twitter sweep 20260524. X: https://x.com/BrollUganda. Public reference: https://twitter.com/BrollUganda/with_replies. Profile created because the account is a recurring real-estate services source with a website and repeated property-market posts.'),
    ('Chris Property Uganda Ltd', 'Chris Property Uganda Ltd', 'SOCIAL-CHRIS-PROPERTY-UGANDA-X-20260524', '+256756917480', '+256756917480', NULL, ARRAY['Kampala','Wakiso','Mukono','Entebbe']::text[], ARRAY['X/Twitter property source','Land for sale','Houses for sale','Rentals']::text[], NULL, 'Chris Property Uganda Ltd is a recurring X/Twitter property source with public sale/rent/land posts. Exact post imports still require source URLs, first-posted dates, and authorised images/stills.', 'Social-first X/Twitter sweep 20260524. X: https://x.com/chrispropertyug. Public reference: https://mobile.twstalker.com/chrispropertyug. Profile created because public evidence shows repeated plots and houses posted from the same source.'),
    ('Ecoland Property Services', 'Ecoland Property Services', 'SOCIAL-ECOLAND-PROPERTY-SERVICES-X-20260524', '+256755700700', '+256755700700', 'info@ecolandproperty.com', ARRAY['Kampala','Wakiso','Mukono','Entebbe','Luwero']::text[], ARRAY['X/Twitter property source','Land for sale','Houses for sale','Rentals','Commercial property']::text[], NULL, 'Ecoland Property Services is a recurring Uganda property source added from the social-first X/Twitter sweep. Exact X post imports still require source URLs, first-posted dates, and authorised images/stills.', 'Social-first X/Twitter sweep 20260524. X: https://x.com/ecolandproperty. Website evidence: https://www.ecolandproperty.com/author/contentadmin/. Profile created because public evidence shows repeated sale/rent property inventory.'),
    ('Bigways', 'Bigways', 'SOCIAL-BIGWAYS-UG-X-20260524', '+256703200619', '+256703200619', NULL, ARRAY['Kampala','Wakiso']::text[], ARRAY['X/Twitter property source','Real estate deals','Land for sale','Homes for sale']::text[], NULL, 'Bigways is a Kampala/Wakiso real-estate-deals source added from the social-first X/Twitter sweep. Exact post imports still require source URLs, first-posted dates, and authorised images/stills.', 'Social-first X/Twitter sweep 20260524. X: https://x.com/Bigways_UG. Public reference: https://twitter.com/Bigways_UG/with_replies. Profile created because public evidence says buy and sell properties in Kampala/Wakiso and references Facebook-page presence.'),
    ('Knight Frank Uganda', 'Knight Frank Uganda', 'SOCIAL-KNIGHT-FRANK-UGANDA-20260524', '+256752741391', '+256752741391', 'info@ug.knightfrank.com', ARRAY['Kampala','Wakiso']::text[], ARRAY['X/Twitter property source','Commercial property','Residential property','Property management']::text[], NULL, 'Knight Frank Uganda is an established recurring Uganda property source. This update adds X/Twitter as a priority social source alongside TikTok/Facebook/website review.', 'Social-first X/Twitter sweep 20260524. X: https://x.com/knightfrankug. Public reference: https://mobile.twstalker.com/knightfrankug.')
),
updated_agents AS (
  UPDATE agents a
  SET
    full_name = ap.full_name,
    company_name = ap.company_name,
    licence_number = ap.licence_number,
    registration_status = 'registered',
    listing_limit = 2147483647,
    phone = COALESCE(ap.phone, a.phone),
    whatsapp = COALESCE(ap.whatsapp, a.whatsapp),
    email = COALESCE(ap.email, a.email),
    districts_covered = ap.districts_covered,
    specializations = ap.specializations,
    profile_photo_url = COALESCE(ap.profile_photo_url, a.profile_photo_url),
    bio = ap.bio,
    verification_reason = ap.verification_reason,
    privacy_consent_accepted = TRUE,
    privacy_consent_at = COALESCE(a.privacy_consent_at, NOW()),
    data_retention_notice_accepted = TRUE,
    data_retention_notice_at = COALESCE(a.data_retention_notice_at, NOW()),
    status = 'approved',
    approved_at = COALESCE(a.approved_at, NOW()),
    updated_at = NOW()
  FROM agent_profiles ap
  WHERE a.licence_number = ap.licence_number
     OR (ap.phone IS NOT NULL AND (a.phone = ap.phone OR a.whatsapp = ap.phone))
     OR (ap.email IS NOT NULL AND LOWER(COALESCE(a.email, '')) = LOWER(ap.email))
  RETURNING a.licence_number
)
INSERT INTO agents (
  full_name,
  company_name,
  licence_number,
  registration_status,
  listing_limit,
  phone,
  whatsapp,
  email,
  districts_covered,
  specializations,
  profile_photo_url,
  bio,
  verification_reason,
  privacy_consent_accepted,
  privacy_consent_at,
  data_retention_notice_accepted,
  data_retention_notice_at,
  status,
  approved_at
)
SELECT
  ap.full_name,
  ap.company_name,
  ap.licence_number,
  'registered',
  2147483647,
  ap.phone,
  ap.whatsapp,
  ap.email,
  ap.districts_covered,
  ap.specializations,
  ap.profile_photo_url,
  ap.bio,
  ap.verification_reason,
  TRUE,
  NOW(),
  TRUE,
  NOW(),
  'approved',
  NOW()
FROM agent_profiles ap
WHERE NOT EXISTS (
  SELECT 1
  FROM agents a
  WHERE a.licence_number = ap.licence_number
     OR (ap.phone IS NOT NULL AND (a.phone = ap.phone OR a.whatsapp = ap.phone))
     OR (ap.email IS NOT NULL AND LOWER(COALESCE(a.email, '')) = LOWER(ap.email))
);
