-- Add the four Kenya off-plan projects supplied by Karim on 2026-09-10.
-- These are explicitly approved source previews. Missing facts remain labelled
-- as pending and do not pass the stricter fully-verified publication gate.

INSERT INTO off_plan_developments (
  country_code, slug, name, developer_name, source_display_name, status,
  verification_status, description, area, district, address, latitude,
  longitude, project_type, completion_date, launch_price_ugx,
  original_currency, reservation_fee_ugx, payment_plan_months, unit_types,
  payment_plan, images, floor_plans, amenities, nearby_places,
  brochure_settings, extra_fields, published_at
) VALUES
(
  'KE',
  'velar',
  'Velar',
  NULL,
  'Karim - supplied Velar project renders',
  'published',
  'partially_verified',
  'Velar is a Kenya residential project presented in the supplied architectural renders with a tower, landscaped rooftop spaces and a rooftop pool. The exact location, developer identity, unit mix, prices, payment plan, programme, approvals and current availability were not included in the supplied pack and must be confirmed before any commitment or payment.',
  'Location to be confirmed',
  'Kenya',
  'Kenya - exact project address to be confirmed',
  NULL,
  NULL,
  'Residential development',
  NULL,
  NULL,
  'KES',
  NULL,
  NULL,
  '[
    {"key":"residences","label":"Residences - details to be confirmed","bedrooms":null,"property_type":"Residence","size_sqm":null,"price_original":null,"price_original_currency":"KES","price_ugx":null,"price_status":"Current unit mix and prices to be confirmed with makaug.com"}
  ]'::jsonb,
  '[]'::jsonb,
  '[
    {"url":"/assets/off-plan/velar/tower-at-sunset.jpg","caption":"Artist impression labelled Velar in the supplied Karim render pack; location, final design and finishes must be confirmed","kind":"artist_impression"},
    {"url":"/assets/off-plan/velar/rooftop-overview.jpg","caption":"Artist impression of a landscaped rooftop supplied for Velar; final layout and facilities may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/velar/rooftop-pool.jpg","caption":"Artist impression of a rooftop pool supplied for Velar; final layout and facilities may differ","kind":"artist_impression"}
  ]'::jsonb,
  '[]'::jsonb,
  '["Landscaped rooftop shown in supplied renders","Rooftop pool shown in supplied renders"]'::jsonb,
  '[]'::jsonb,
  '{"brand":"makaug.com","footer_url":"https://makaug.com/off-plan/overseas/kenya/velar","contact_mode":"makaug_managed","cover_image":"/assets/off-plan/velar/tower-at-sunset.jpg"}'::jsonb,
  '{
    "public_preview_approved":true,
    "public_preview_approved_source":"site_owner_request_2026_09_10",
    "contact_mode":"makaug_managed",
    "source_materials_verified":true,
    "source_documents_verified":false,
    "source":"karim_supplied_velar_render_pack_2026_09_10",
    "source_documents":[{"filename":"VELAR.zip","sha256":"abdf0e9263c9f7ec8e9d9131310738af52f571dd47d9ddbfc11cceb7271686ec","bytes":24296208,"purpose":"supplied project render pack; no brochure included"}],
    "price_on_request_approved":true,
    "price_status":"Current unit mix and prices to be confirmed with makaug.com.",
    "payment_plan_pending_approved":true,
    "payment_plan_status":"A payment plan was not included in the supplied pack; confirm current terms with makaug.com.",
    "map_point_pending_approved":true,
    "map_precision":"exact_pin_pending",
    "country_name":"Kenya",
    "country_slug":"kenya",
    "region":"Africa",
    "public_path":"/off-plan/overseas/kenya/velar",
    "area_overview":"The supplied Velar pack contains architectural renders only. Confirm the county, neighbourhood, exact site entrance and travel times before visiting or making a commitment.",
    "payment_terms_note":"No booking fee, deposit, installment schedule or completion-linked payment terms were included in the supplied render pack. Obtain and independently review the current developer offer letter and sale agreement before paying.",
    "overseas_finance_policy":"Ask your bank whether it can finance a Kenyan off-plan purchase, what security it requires and how construction-stage payments are handled.",
    "makaug_service_steps":["Initial requirements and affordability call","Obtain and review the developer brochure and sale documents","Independent Kenyan lawyer and title checks","Developer and offer-letter coordination","Bank and payment coordination","Milestone follow-up through handover"],
    "official_buyer_guidance":[
      {"label":"Kenya Ministry of Lands - official search certificate","url":"https://lands.go.ke/issuance-search-certificate","note":"Use the official land-registry process and an independent Kenyan lawyer to verify the registered owner, title and encumbrances."},
      {"label":"Kenya Land Registration Act","url":"https://new.kenyalaw.org/akn/ke/act/2012/3/eng@2022-12-31","note":"Review the current legal framework with an independent Kenyan lawyer before signing or transferring funds."}
    ],
    "confirmed_source_fields":["project name shown in a supplied render","tower form shown in supplied renders","landscaped rooftop shown in supplied renders","rooftop pool shown in supplied renders"],
    "facts_to_confirm":["developer legal identity","county and neighbourhood","exact site address and map pin","unit mix and sizes","current prices and availability","booking fee and payment plan","expected completion date","construction progress","total units and units sold","planning and regulatory approvals","service charges and transaction fees"]
  }'::jsonb,
  NOW()
),
(
  'KE',
  'ivy-myst-kileleshwa',
  'Ivy Myst',
  'Karim Real Estate',
  'Karim - supplied Ivy Myst developer brochure',
  'published',
  'partially_verified',
  'Ivy Myst is an off-plan wellness-focused apartment development presented for Gatundu Road in Kileleshwa, Nairobi. The supplied brochure describes one-, two- and three-bedroom residences, a layered rooftop wellness programme and cash or quarterly installment options. Current availability, completion timing, approvals, service charges and final sale terms must be confirmed before payment.',
  'Kileleshwa',
  'Nairobi',
  'Gatundu Road, Kileleshwa, Nairobi, Kenya',
  -1.2782974,
  36.7848211,
  'Wellness apartment development',
  NULL,
  230996000,
  'KES',
  NULL,
  15,
  '[
    {"key":"one-bedroom","label":"1 Bedroom apartment","bedrooms":1,"property_type":"Apartment","size_sqm_min":78,"size_sqm_max":84,"price_original":7900000,"price_original_max":10500000,"price_original_currency":"KES","price_ugx":230996000,"price_ugx_max":307020000,"price_fx_rate_ugx":29.24},
    {"key":"two-bedroom","label":"2 Bedroom apartment","bedrooms":2,"property_type":"Apartment","size_sqm_min":121,"size_sqm_max":159,"price_original":14200000,"price_original_max":20400000,"price_original_currency":"KES","price_ugx":415208000,"price_ugx_max":596496000,"price_fx_rate_ugx":29.24},
    {"key":"three-bedroom","label":"3 Bedroom apartment","bedrooms":3,"property_type":"Apartment","size_sqm_min":169,"size_sqm_max":231,"price_original":19800000,"price_original_max":29600000,"price_original_currency":"KES","price_ugx":578952000,"price_ugx_max":865504000,"price_fx_rate_ugx":29.24}
  ]'::jsonb,
  '[
    {"key":"installment-deposit","label":"Installment-plan deposit","kind":"percentage","percent":20,"currency":"KES","due":"Within seven days of the offer letter","source_confirmed":true,"staff_verified":false},
    {"key":"quarterly-installments","label":"Five quarterly installments","kind":"percentage","percent":50,"installments":5,"months":15,"currency":"KES","due":"10 percent every quarter for five quarters","source_confirmed":true,"staff_verified":false},
    {"key":"completion-balance","label":"Balance on or before completion","kind":"percentage","percent":30,"currency":"KES","due":"On or before completion","source_confirmed":true,"staff_verified":false},
    {"key":"cash-deposit","label":"Cash-option deposit","kind":"percentage","percent":20,"currency":"KES","due":"At booking under the cash option","source_confirmed":true,"staff_verified":false},
    {"key":"cash-balance","label":"Cash-option balance","kind":"percentage","percent":80,"currency":"KES","due":"Within 30 days under the cash option","source_confirmed":true,"staff_verified":false}
  ]'::jsonb,
  '[
    {"url":"/assets/off-plan/ivy-myst-kileleshwa/facade.jpg","caption":"Artist impression of the Ivy Myst facade from the supplied brochure; final design and finishes may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/ivy-myst-kileleshwa/rooftop-residences.jpg","caption":"Artist impression of Ivy Myst rooftop residences from the supplied brochure; final design and views may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/ivy-myst-kileleshwa/arrival.jpg","caption":"Artist impression of the Ivy Myst arrival from the supplied brochure; final finishes may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/ivy-myst-kileleshwa/indoor-zen-garden.jpg","caption":"Artist impression of the indoor zen garden from the supplied brochure; final facilities may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/ivy-myst-kileleshwa/kids-play-room.jpg","caption":"Artist impression of the kids play room from the supplied brochure; final facilities may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/ivy-myst-kileleshwa/strength-gym.jpg","caption":"Artist impression of the strength gym from the supplied brochure; final facilities may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/ivy-myst-kileleshwa/thermal-heated-pool.jpg","caption":"Artist impression of the thermal heated pool from the supplied brochure; final facilities may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/ivy-myst-kileleshwa/sky-restaurant.jpg","caption":"Artist impression of the sky restaurant from the supplied brochure; final facilities may differ","kind":"artist_impression"}
  ]'::jsonb,
  '[]'::jsonb,
  '["Courtyard","Indoor zen garden","Thermal heated pool","Work sanctuary","Kids play room","Strength gym","Sauna and massage room","Aqua sky bar","Upper water lounge","Firepit lounge","Celestial pool","Cardio gym","Sky yoga","Sky restaurant"]'::jsonb,
  '[]'::jsonb,
  '{"brand":"makaug.com","footer_url":"https://makaug.com/off-plan/overseas/kenya/ivy-myst-kileleshwa","contact_mode":"makaug_managed","cover_image":"/assets/off-plan/ivy-myst-kileleshwa/facade.jpg"}'::jsonb,
  '{
    "public_preview_approved":true,
    "public_preview_approved_source":"site_owner_request_2026_09_10",
    "contact_mode":"makaug_managed",
    "source_documents_verified":true,
    "source":"karim_supplied_ivy_myst_brochure_2026_09_10",
    "source_documents":[{"filename":"IVY MYST PRINT & PREVIEW EXTERNAL.pdf","sha256":"67ee785d8ff32d2a18f2891ae7359a842a26d31f09119e4986a48a8ee626dc62","bytes":7892512,"purpose":"developer project brochure"}],
    "map_precision":"area_centroid",
    "map_note":"Gatundu Road area marker, not the exact project entrance.",
    "country_name":"Kenya",
    "country_slug":"kenya",
    "region":"Africa",
    "public_path":"/off-plan/overseas/kenya/ivy-myst-kileleshwa",
    "price_fx_rate_ugx":29.24,
    "price_fx_basis":"Indicative KES to UGX conversion only; refresh the exchange rate before relying on it.",
    "price_fx_as_of":"2026-09-10",
    "developer_role":"The supplied brochure states that Ivy Myst was conceptualised by Karim Real Estate.",
    "developer_website":"https://ivymyst.ke/",
    "area_overview":"The supplied brochure places Ivy Myst on Gatundu Road in Kileleshwa. The map marker represents the road area rather than a verified project entrance; confirm the exact entrance and current travel times before visiting.",
    "payment_terms_note":"The supplied brochure lists a 20 percent deposit within seven days of the offer letter, 10 percent every quarter for five quarters and 30 percent on or before completion. It also presents a cash option of 20 percent followed by 80 percent within 30 days. Confirm the current offer, dates, account details, taxes, fees and refund terms in the signed sale documents.",
    "overseas_finance_policy":"Ask your bank whether it can finance a Kenyan off-plan purchase, what security it requires and how KES transfers and construction-stage payments are handled.",
    "makaug_service_steps":["Initial requirements and affordability call","Source and project-document review","Independent Kenyan lawyer and title checks","Developer and offer-letter coordination","Bank and foreign-currency payment coordination","Milestone follow-up through handover"],
    "official_buyer_guidance":[
      {"label":"Kenya Ministry of Lands - official search certificate","url":"https://lands.go.ke/issuance-search-certificate","note":"Use the official land-registry process and an independent Kenyan lawyer to verify the registered owner, title and encumbrances."},
      {"label":"Kenya Land Registration Act","url":"https://new.kenyalaw.org/akn/ke/act/2012/3/eng@2022-12-31","note":"Review the current legal framework with an independent Kenyan lawyer before signing or transferring funds."}
    ],
    "confirmed_source_fields":["project name","Gatundu Road and Kileleshwa location labels","Karim Real Estate conceptualisation statement","one, two and three bedroom unit mix","supplied size and price ranges","cash and installment payment options","supplied amenity list"],
    "facts_to_confirm":["developer contracting entity","exact site entrance","current unit availability and prices","expected completion date","construction progress","total units and units sold","planning and regulatory approvals","service charges","transaction taxes and fees","final payment dates and refund terms"]
  }'::jsonb,
  NOW()
),
(
  'KE',
  'high-street-lane-migaa',
  'High Street Lane',
  NULL,
  'Karim Exclusives - supplied High Street Lane agent and floor-plan brochures',
  'published',
  'partially_verified',
  'High Street Lane is a mixed-use off-plan residential development presented for Migaa in Kiambu County, with studios and one- to four-bedroom homes arranged across phased blocks, a retail parade and resident rooftop amenities. The supplied brochure lists phase targets and cash or quarterly payment options; developer identity, approvals, current availability and final sale terms must be confirmed before payment.',
  'Migaa',
  'Kiambu County',
  'Migaa, Kiambu County, Kenya',
  -1.3552630,
  36.8910320,
  'Mixed-use residential development',
  '2027-09-30',
  95030000,
  'KES',
  NULL,
  36,
  '[
    {"key":"studio-duplex-pair","label":"Studio paired with duplex","bedrooms":0,"property_type":"Studio","size_sqm":32.5,"price_original":3250000,"price_original_currency":"KES","price_ugx":95030000,"price_fx_rate_ugx":29.24},
    {"key":"studio-corner-duplex-pair","label":"Corner studio paired with duplex","bedrooms":0,"property_type":"Studio","size_sqm":37.5,"price_original":3750000,"price_original_currency":"KES","price_ugx":109650000,"price_fx_rate_ugx":29.24},
    {"key":"one-bedroom-triplex-detachment","label":"1 Bedroom apartment / triplex detachment","bedrooms":1,"property_type":"Apartment","size_sqm":57.5,"price_original":5750000,"price_original_currency":"KES","price_ugx":168130000,"price_fx_rate_ugx":29.24},
    {"key":"one-bedroom-duplex-pair","label":"1 Bedroom duplex paired with triplex","bedrooms":1,"property_type":"Duplex","size_sqm":60,"price_original":6000000,"price_original_currency":"KES","price_ugx":175440000,"price_fx_rate_ugx":29.24},
    {"key":"one-bedroom-corner-duplex-pair","label":"1 Bedroom corner duplex paired with triplex","bedrooms":1,"property_type":"Duplex","size_sqm":70,"price_original":7000000,"price_original_currency":"KES","price_ugx":204680000,"price_fx_rate_ugx":29.24},
    {"key":"two-bedroom-duplex","label":"2 Bedroom duplex","bedrooms":2,"property_type":"Duplex","size_sqm":135,"price_original":13500000,"price_original_currency":"KES","price_ugx":394740000,"price_fx_rate_ugx":29.24},
    {"key":"two-bedroom-garden-duplex","label":"2 Bedroom garden duplex","bedrooms":2,"property_type":"Duplex","size_sqm":132.5,"price_original":14750000,"price_original_currency":"KES","price_ugx":431290000,"price_fx_rate_ugx":29.24},
    {"key":"three-bedroom-garden-triplex","label":"3 Bedroom garden triplex","bedrooms":3,"property_type":"Triplex","size_sqm":190,"price_original":19000000,"price_original_currency":"KES","price_ugx":555560000,"price_fx_rate_ugx":29.24},
    {"key":"four-bedroom-garden-triplex","label":"4 Bedroom garden triplex","bedrooms":4,"property_type":"Triplex","size_sqm":190,"price_original":20500000,"price_original_currency":"KES","price_ugx":599420000,"price_fx_rate_ugx":29.24}
  ]'::jsonb,
  '[
    {"key":"cash-deposit","label":"Cash-option deposit","kind":"percentage","percent":20,"currency":"KES","due":"At booking","source_confirmed":true,"staff_verified":false},
    {"key":"cash-balance","label":"Cash-option balance","kind":"percentage","percent":80,"currency":"KES","due":"Within 30 days","source_confirmed":true,"staff_verified":false},
    {"key":"phase-plan-deposit","label":"Phase payment-plan deposit","kind":"percentage","percent":20,"currency":"KES","due":"At booking","source_confirmed":true,"staff_verified":false},
    {"key":"phase-plan-balance","label":"Phase payment-plan balance","kind":"quarterly","percent":80,"months":36,"currency":"KES","due":"Quarterly across the applicable one-, two- or three-year phase period","source_confirmed":true,"staff_verified":false}
  ]'::jsonb,
  '[
    {"url":"/assets/off-plan/high-street-lane-migaa/facade-panorama.jpg","caption":"Artist impression of High Street Lane from the supplied agent brochure; final design and finishes may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/high-street-lane-migaa/festival-arcade.jpg","caption":"Artist impression of the festival arcade from the supplied agent brochure; final layout and uses may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/high-street-lane-migaa/boulevard.jpg","caption":"Artist impression of the High Street Lane boulevard from the supplied agent brochure; final layout may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/high-street-lane-migaa/retail-parade.jpg","caption":"Artist impression of the retail parade from the supplied agent brochure; final occupiers and layout may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/high-street-lane-migaa/resident-amenities.jpg","caption":"Artist impression of resident amenities from the supplied agent brochure; final facilities may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/high-street-lane-migaa/rooftop-pet-park.jpg","caption":"Artist impression of the rooftop pet park from the supplied agent brochure; final facilities may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/high-street-lane-migaa/rooftop-koroga.jpg","caption":"Artist impression of the rooftop BBQ and koroga area from the supplied agent brochure; final facilities may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/high-street-lane-migaa/giant-chess.jpg","caption":"Artist impression of the giant chess area from the supplied agent brochure; final facilities may differ","kind":"artist_impression"}
  ]'::jsonb,
  '[
    {"url":"/assets/off-plan/high-street-lane-migaa/floor-plan-block-a-page-3.jpg","caption":"Block A floor-plan sheet, page 3, rendered from the supplied brochure","kind":"floor_plan"},
    {"url":"/assets/off-plan/high-street-lane-migaa/floor-plan-block-a-page-4.jpg","caption":"Block A floor-plan sheet, page 4, rendered from the supplied brochure","kind":"floor_plan"},
    {"url":"/assets/off-plan/high-street-lane-migaa/floor-plan-block-a-page-5.jpg","caption":"Block A floor-plan sheet, page 5, rendered from the supplied brochure","kind":"floor_plan"},
    {"url":"/assets/off-plan/high-street-lane-migaa/floor-plan-block-a-page-6.jpg","caption":"Block A floor-plan sheet, page 6, rendered from the supplied brochure","kind":"floor_plan"},
    {"url":"/assets/off-plan/high-street-lane-migaa/floor-plan-block-a-page-7.jpg","caption":"Block A floor-plan sheet, page 7, rendered from the supplied brochure","kind":"floor_plan"},
    {"url":"/assets/off-plan/high-street-lane-migaa/floor-plan-block-a-page-8.jpg","caption":"Block A floor-plan sheet, page 8, rendered from the supplied brochure","kind":"floor_plan"},
    {"url":"/assets/off-plan/high-street-lane-migaa/floor-plan-block-b-page-8.jpg","caption":"Block B floor-plan sheet, page 8, rendered from the supplied brochure","kind":"floor_plan"}
  ]'::jsonb,
  '["Rooftop pet park","Rooftop BBQ and koroga area","Rooftop jogging track","Giant chess","Retail parade","Padel court","Beauty parlour","Dry cleaner","Health clinic","Supermarket","Swimming pool","Fitness gym","Pharmacy","Restaurant","Sky garden"]'::jsonb,
  '[]'::jsonb,
  '{"brand":"makaug.com","footer_url":"https://makaug.com/off-plan/overseas/kenya/high-street-lane-migaa","contact_mode":"makaug_managed","cover_image":"/assets/off-plan/high-street-lane-migaa/facade-panorama.jpg"}'::jsonb,
  '{
    "public_preview_approved":true,
    "public_preview_approved_source":"site_owner_request_2026_09_10",
    "contact_mode":"makaug_managed",
    "source_documents_verified":true,
    "source":"karim_supplied_high_street_lane_agent_and_floor_plan_brochures_2026_09_10",
    "source_documents":[
      {"filename":"HIGH STREET LANE - AGENTS BROCHURE.pdf","sha256":"ccc3840711b99b438efa6e4e5e8047172a96ca12c5d319a7b129b5058d39c69d","bytes":11134659,"purpose":"agent project, pricing and payment brochure"},
      {"filename":"MIGAA Highstreet Block-A V2.pdf","sha256":"dcdb72c6c6829ce6413361ee6fbc57a4165f5d4ad0925d2c782382096311dd8e","bytes":4740303,"purpose":"Block A floor-plan brochure"},
      {"filename":"MIGAA Highstreet Block-B V2.pdf","sha256":"f015e41a4c2f45ccbcbda8cce2a6a7eff844dab91fd53e62a7b68d360baafd9b","bytes":4789066,"purpose":"Block B floor-plan brochure"}
    ],
    "map_precision":"source_coordinates",
    "map_note":"Coordinates printed in the supplied agent brochure; confirm the exact visitor entrance.",
    "country_name":"Kenya",
    "country_slug":"kenya",
    "region":"Africa",
    "public_path":"/off-plan/overseas/kenya/high-street-lane-migaa",
    "price_fx_rate_ugx":29.24,
    "price_fx_basis":"Indicative KES to UGX conversion only; refresh the exchange rate before relying on it.",
    "price_fx_as_of":"2026-09-10",
    "completion_source_label":"Phase 1 target September 2027; Phase 2 target September 2028; Phase 3 target September 2029.",
    "phase_summary":[{"phase":"Phase 1","blocks":"1-3","target":"September 2027"},{"phase":"Phase 2","blocks":"4-6","target":"September 2028"},{"phase":"Phase 3","blocks":"7-9","target":"September 2029"}],
    "release_size_note":"The supplied brochure states 48 units per phase.",
    "area_overview":"The supplied brochure places High Street Lane in Migaa, Kiambu County and prints a coordinate point for the project. Confirm the exact visitor entrance, access route and current journey times before visiting.",
    "payment_terms_note":"The supplied brochure lists a 20 percent deposit and 80 percent within 30 days for cash purchases. It also lists a 20 percent deposit with the balance paid quarterly across one, two or three years according to the applicable phase. Studios are marked cash only. Confirm the exact schedule, account details, taxes, fees and refund terms in the signed sale documents.",
    "overseas_finance_policy":"Ask your bank whether it can finance a Kenyan off-plan purchase, what security it requires and how KES transfers and construction-stage payments are handled.",
    "makaug_service_steps":["Initial requirements and affordability call","Source and project-document review","Independent Kenyan lawyer and title checks","Developer and offer-letter coordination","Bank and foreign-currency payment coordination","Milestone follow-up through handover"],
    "official_buyer_guidance":[
      {"label":"Kenya Ministry of Lands - official search certificate","url":"https://lands.go.ke/issuance-search-certificate","note":"Use the official land-registry process and an independent Kenyan lawyer to verify the registered owner, title and encumbrances."},
      {"label":"Kenya Land Registration Act","url":"https://new.kenyalaw.org/akn/ke/act/2012/3/eng@2022-12-31","note":"Review the current legal framework with an independent Kenyan lawyer before signing or transferring funds."}
    ],
    "confirmed_source_fields":["project name","Migaa and Kiambu County location labels","source coordinate point","studio through four bedroom unit mix","supplied unit sizes and prices","cash and phased payment options","48 units per phase statement","phase target dates","supplied amenity list","Block A and Block B floor-plan sheets"],
    "facts_to_confirm":["developer contracting entity","exact visitor entrance","current unit availability and prices","construction progress and actual start","planning and regulatory approvals","total units and units sold","service charges","transaction taxes and fees","final installment dates and refund terms"]
  }'::jsonb,
  NOW()
),
(
  'KE',
  'gaia-brookside',
  'Gaia Brookside',
  'Wonder Properties',
  'Karim - supplied Gaia Brookside developer brochure and renders',
  'published',
  'partially_verified',
  'Gaia Brookside is an off-plan residential development presented for the Brookside area of Westlands, Nairobi, with three-, four- and five-bedroom residences and a broad set of wellness, leisure and rooftop amenities. The supplied brochure identifies Wonder Properties, while current payment terms, completion timing, stock, approvals and final sale terms must be confirmed before payment.',
  'Brookside',
  'Nairobi',
  'Brookside, Westlands, Nairobi, Kenya',
  -1.2558094,
  36.7886829,
  'Luxury apartment development',
  NULL,
  731000000,
  'KES',
  NULL,
  NULL,
  '[
    {"key":"three-bedroom","label":"3 Bedroom residence","bedrooms":3,"property_type":"Residence","size_sqm":null,"price_original":25000000,"price_original_currency":"KES","price_ugx":731000000,"price_fx_rate_ugx":29.24,"price_status":"Project-level starting price; confirm the exact unit price and size"},
    {"key":"four-bedroom","label":"4 Bedroom residence","bedrooms":4,"property_type":"Residence","size_sqm":null,"price_original":null,"price_original_currency":"KES","price_ugx":null,"price_status":"Current price and size to be confirmed with makaug.com"},
    {"key":"five-bedroom","label":"5 Bedroom residence","bedrooms":5,"property_type":"Residence","size_sqm":null,"price_original":null,"price_original_currency":"KES","price_ugx":null,"price_status":"Current price and size to be confirmed with makaug.com"}
  ]'::jsonb,
  '[]'::jsonb,
  '[
    {"url":"/assets/off-plan/gaia-brookside/exterior.jpg","caption":"Artist impression of the Gaia Brookside exterior from current project materials; final design and finishes may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/gaia-brookside/residence-lounge.jpg","caption":"Artist impression of a Gaia Brookside residence lounge from the supplied brochure; final finishes may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/gaia-brookside/dining-area.jpg","caption":"Artist impression of a Gaia Brookside dining area from the supplied brochure; final finishes may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/gaia-brookside/kitchen.jpg","caption":"Artist impression of a Gaia Brookside kitchen from the supplied brochure; final finishes may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/gaia-brookside/bedroom.jpg","caption":"Artist impression of a Gaia Brookside bedroom from the supplied brochure; final finishes may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/gaia-brookside/balcony.jpg","caption":"Artist impression of a Gaia Brookside balcony from the supplied brochure; final views and finishes may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/gaia-brookside/home-office.jpg","caption":"Artist impression of a Gaia Brookside home office from the supplied brochure; final finishes may differ","kind":"artist_impression"},
    {"url":"/assets/off-plan/gaia-brookside/bathroom.jpg","caption":"Artist impression of a Gaia Brookside bathroom from the supplied brochure; final finishes may differ","kind":"artist_impression"}
  ]'::jsonb,
  '[]'::jsonb,
  '["Elemental garden","Reception","Conference room","Coffee shop","Childrens play area","Fitness centre","Yoga studio","Healthcare centre","Serenity spa","Swimming pool","Rooftop lounge and bar","Koroga and BBQ area","Rooftop jogging track","Tennis court","Snookball","Rooftop yoga","Pet area","Rooftop seating","Helipad"]'::jsonb,
  '[]'::jsonb,
  '{"brand":"makaug.com","footer_url":"https://makaug.com/off-plan/overseas/kenya/gaia-brookside","contact_mode":"makaug_managed","cover_image":"/assets/off-plan/gaia-brookside/exterior.jpg"}'::jsonb,
  '{
    "public_preview_approved":true,
    "public_preview_approved_source":"site_owner_request_2026_09_10",
    "contact_mode":"makaug_managed",
    "source_documents_verified":true,
    "source":"karim_supplied_gaia_brookside_brochure_and_renders_2026_09_10",
    "source_documents":[{"filename":"Gaia Brookside Brochure - Web.pdf","sha256":"93811aa82f2d28eaba9ceaa7d22574759818913c98af0579e4f31fb54bc7ac29","bytes":41178188,"purpose":"developer project brochure"}],
    "payment_plan_pending_approved":true,
    "payment_plan_status":"A payment schedule was not included in the supplied brochure; confirm current terms with makaug.com.",
    "map_precision":"area_centroid",
    "map_note":"Brookside Gardens road-area marker, not the exact project entrance.",
    "country_name":"Kenya",
    "country_slug":"kenya",
    "region":"Africa",
    "public_path":"/off-plan/overseas/kenya/gaia-brookside",
    "price_fx_rate_ugx":29.24,
    "price_fx_basis":"Indicative KES to UGX conversion only; refresh the exchange rate before relying on it.",
    "price_fx_as_of":"2026-09-10",
    "starting_price_source_note":"The current project website presents a project-level starting price of KES 25 million; confirm the exact unit and live price.",
    "developer_website":"https://gaiabrookside.co.ke/",
    "area_overview":"The supplied brochure maps Gaia Brookside around Brookside Drive, Brookside Gardens, Matundu Lane and School Lane in Westlands. The map marker represents the road area rather than a verified project entrance; confirm the exact entrance and current travel times before visiting.",
    "payment_terms_note":"No booking fee, deposit or installment schedule was included in the supplied brochure. Obtain and independently review the current developer offer letter and sale agreement before paying.",
    "overseas_finance_policy":"Ask your bank whether it can finance a Kenyan off-plan purchase, what security it requires and how KES transfers and construction-stage payments are handled.",
    "makaug_service_steps":["Initial requirements and affordability call","Source and project-document review","Independent Kenyan lawyer and title checks","Developer and offer-letter coordination","Bank and foreign-currency payment coordination","Milestone follow-up through handover"],
    "official_buyer_guidance":[
      {"label":"Kenya Ministry of Lands - official search certificate","url":"https://lands.go.ke/issuance-search-certificate","note":"Use the official land-registry process and an independent Kenyan lawyer to verify the registered owner, title and encumbrances."},
      {"label":"Kenya Land Registration Act","url":"https://new.kenyalaw.org/akn/ke/act/2012/3/eng@2022-12-31","note":"Review the current legal framework with an independent Kenyan lawyer before signing or transferring funds."}
    ],
    "confirmed_source_fields":["project name","Wonder Properties developer name","Brookside area labels","three, four and five bedroom unit mix on the project website","project-level starting price on the project website","supplied amenity list"],
    "facts_to_confirm":["exact site entrance and map pin","current unit sizes, prices and availability","booking fee and payment plan","expected completion date","construction progress","total units and units sold","planning and regulatory approvals","service charges","transaction taxes and fees","final payment dates and refund terms"]
  }'::jsonb,
  NOW()
)
ON CONFLICT (country_code, slug) DO UPDATE SET
  name = EXCLUDED.name,
  developer_name = EXCLUDED.developer_name,
  source_display_name = EXCLUDED.source_display_name,
  status = EXCLUDED.status,
  verification_status = CASE WHEN off_plan_developments.verification_status = 'verified' THEN off_plan_developments.verification_status ELSE EXCLUDED.verification_status END,
  description = EXCLUDED.description,
  area = EXCLUDED.area,
  district = EXCLUDED.district,
  address = EXCLUDED.address,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  project_type = EXCLUDED.project_type,
  completion_date = EXCLUDED.completion_date,
  launch_price_ugx = EXCLUDED.launch_price_ugx,
  original_currency = EXCLUDED.original_currency,
  reservation_fee_ugx = EXCLUDED.reservation_fee_ugx,
  payment_plan_months = EXCLUDED.payment_plan_months,
  unit_types = EXCLUDED.unit_types,
  payment_plan = EXCLUDED.payment_plan,
  images = EXCLUDED.images,
  floor_plans = EXCLUDED.floor_plans,
  amenities = EXCLUDED.amenities,
  nearby_places = EXCLUDED.nearby_places,
  brochure_settings = EXCLUDED.brochure_settings,
  extra_fields = EXCLUDED.extra_fields,
  published_at = COALESCE(off_plan_developments.published_at, NOW()),
  updated_at = NOW();
