'use strict';

/**
 * Asking for the money, and telling the people who need to know.
 *
 * The fee started on 5 Oct 2026 — UGX 50,000 a month. Until now approving an
 * agent sent the welcome pack and nothing else: no pay link was generated by
 * approval, and none by the Agent 007 path that registered them. An agent could
 * go live, be welcomed, list property and never once be asked for money. Nobody
 * was told either — "waiting for founder approval" notified no founder, and the
 * employee who brought the agent in was never recorded on the agent at all.
 *
 * Two halves, tested here. The employee is asked on the doorstep whether to
 * send the link, because approval happens days later; and on approval the link
 * goes to the agent while the employee and the owner are told the amount and
 * that it is outstanding.
 */

const test = require('node:test');
const assert = require('node:assert');

const db = require('../config/database');
const route = require('../routes/whatsapp').__test;
const intake = require('../services/whatsappEmployeeIntakeService');
const prospects = require('../services/agentProspectService');

const RONALD = '+256709402189';

// ---------------------------------------------------------------------------
// The question on the doorstep
// ---------------------------------------------------------------------------

test('the fee is quoted from one place, so it cannot drift', () => {
  assert.strictEqual(route.agentMonthlyFeeLabel(), 'UGX 50,000');
  assert.match(intake.employeeAgentPayLinkPrompt('Kato Brian', route.agentMonthlyFeeLabel()),
    /Kato Brian pays UGX 50,000 a month/);
});

test('yes and no are both plainly answerable', () => {
  for (const yes of ['1', 'yes', 'send it', 'ok']) assert.strictEqual(intake.parsePayLinkChoice(yes), 'yes', yes);
  for (const no of ['2', 'no', 'later', 'skip']) assert.strictEqual(intake.parsePayLinkChoice(no), 'no', no);
  assert.strictEqual(intake.parsePayLinkChoice('maybe'), '');
});

function withStubbedDb(run) {
  const originalQuery = db.query;
  const originalGetClient = db.getClient;
  const updates = [];
  let session = null;
  db.query = async (sql, params = []) => {
    if (/UPDATE whatsapp_sessions|INSERT INTO whatsapp_sessions/i.test(sql)) {
      const blob = params.find((p) => typeof p === 'string' && p.trim().startsWith('{'));
      if (blob) session = JSON.parse(blob);
      return { rows: [] };
    }
    if (/UPDATE agents/i.test(sql)) { updates.push({ sql, params }); return { rows: [] }; }
    return { rows: [] };
  };
  db.getClient = async () => ({ query: db.query, release() {} });
  return Promise.resolve(run({ updates, getSession: () => session }))
    .finally(() => { db.query = originalQuery; db.getClient = originalGetClient; });
}

test('the answer is written onto the agent, not just the session', async () => {
  await withStubbedDb(async ({ updates, getSession }) => {
    const result = await route.handleEmployeeWhatsappIntake({
      phone: RONALD,
      body: '1',
      session: {
        current_step: 'employee_agent_pay_link',
        session_data: {
          whatsapp_employee_intake: true,
          employee_role: 'agent',
          new_agent_created: true,
          agent: { id: 'agent-1', full_name: 'Kato Brian' }
        }
      }
    });
    assert.strictEqual(result.nextStep, 'employee_property_count', 'then straight on to the properties');
    assert.match(result.message, /UGX 50,000 link goes to them/);
    assert.strictEqual(getSession().agent_pay_link_on_approval, true);

    const write = updates.find((u) => /pay_link_on_approval/.test(u.sql));
    assert.ok(write, 'the session is wiped by the next batch; approval may be days away');
    assert.strictEqual(write.params[1], true);
    assert.strictEqual(write.params[2], '256709402189',
      'and this is the first time we record which employee brought an agent in');
  });
});

test('saying no means no link is sent on approval', async () => {
  await withStubbedDb(async ({ updates, getSession }) => {
    const result = await route.handleEmployeeWhatsappIntake({
      phone: RONALD,
      body: '2',
      session: {
        current_step: 'employee_agent_pay_link',
        session_data: {
          whatsapp_employee_intake: true,
          employee_role: 'agent',
          new_agent_created: true,
          agent: { id: 'agent-1', full_name: 'Kato Brian' }
        }
      }
    });
    assert.match(result.message, /no payment link will be sent automatically/i);
    assert.strictEqual(getSession().agent_pay_link_on_approval, false);
    assert.strictEqual(updates.find((u) => /pay_link_on_approval/.test(u.sql)).params[1], false);
  });
});

test('an unanswerable reply asks again rather than guessing', async () => {
  await withStubbedDb(async ({ updates }) => {
    const result = await route.handleEmployeeWhatsappIntake({
      phone: RONALD,
      body: 'hmm',
      session: {
        current_step: 'employee_agent_pay_link',
        session_data: {
          whatsapp_employee_intake: true, employee_role: 'agent',
          new_agent_created: true, agent: { id: 'agent-1', full_name: 'Kato Brian' }
        }
      }
    });
    assert.strictEqual(result.nextStep, 'employee_agent_pay_link');
    assert.strictEqual(updates.length, 0, 'nothing may be assumed about money');
  });
});

test('an interrupted intake comes back to the money question', () => {
  assert.strictEqual(
    route.recoverInterruptedEmployeeIntakeStep({
      current_step: 'missed_call_need',
      session_data: {
        whatsapp_employee_intake: true,
        employee_role: 'agent',
        agent_already_registered: false,
        new_agent_details: { fullName: 'Kato Brian' },
        identity_document_url: 'https://cdn.test/id.jpg',
        intake_confirmed: true,
        new_agent_created: true
      }
    }),
    'employee_agent_pay_link'
  );
});

test('an existing agent is not asked about a fee they already pay', () => {
  assert.strictEqual(
    route.recoverInterruptedEmployeeIntakeStep({
      current_step: 'missed_call_need',
      session_data: {
        whatsapp_employee_intake: true,
        employee_role: 'agent',
        agent: { id: 'agent-9' },
        intake_confirmed: true
      }
    }),
    'employee_property_count'
  );
});

// ---------------------------------------------------------------------------
// Prospects — the funnel either side of the agent row
// ---------------------------------------------------------------------------

test('a prospect is keyed by the last nine digits, however it was typed', () => {
  for (const written of ['0772123456', '+256772123456', '256 772 123 456', '772123456']) {
    assert.strictEqual(prospects.prospectPhoneKey(written), '772123456', written);
  }
  assert.strictEqual(prospects.normalizeProspectPhone('0772123456'), '256772123456');
  assert.strictEqual(prospects.normalizeProspectPhone('772123456'), '256772123456');
  assert.ok(prospects.isUsableProspectPhone('0772123456'));
  assert.ok(!prospects.isUsableProspectPhone('07721'));
});

test('every prospect state names the next thing a human has to do', () => {
  assert.match(prospects.prospectNextStep({ status: 'pitched', days_since_pitch: 5 }), /Follow up/);
  assert.match(prospects.prospectNextStep({ status: 'pitched', days_since_pitch: 0 }), /Waiting/);
  assert.match(prospects.prospectNextStep({ status: 'interested' }), /Agent 007/);
  assert.match(prospects.prospectNextStep({ status: 'signed_up' }), /Approve/);
  assert.match(prospects.prospectNextStep({ status: 'approved' }), /Chase the UGX 50,000/);
  assert.match(prospects.prospectNextStep({ status: 'approved', paid_until: '2026-11-05' }), /Done/);
});
