const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');

function run() {
  const migration = read('db/migrations/064_staff_moderator_workbench.sql');
  const auth = read('middleware/auth.js');
  const authFlow = read('services/authFlowService.js');
  const sanitizer = read('services/publicHtmlSanitizer.js');
  const server = read('server.js');
  const staffRoutes = read('routes/staff.js');
  const adminRoutes = read('routes/admin.js');
  const propertyRoutes = read('routes/properties.js');
  const app = read('assets/makaug-app.js');
  const html = read('index.html');

  assert(migration.includes("'moderator'"), 'users role check must include moderator');
  assert(migration.includes('CREATE TABLE IF NOT EXISTS staff_activity_logs'), 'staff activity log table must exist');
  assert(migration.includes('assigned_to_user_id'), 'lead/ad ownership should be assignable to staff users');

  assert(auth.includes('requireStaffAccess'), 'auth middleware must export staff guard');
  assert(auth.includes('requireListingModerationAccess'), 'property publish route must use restricted moderation guard');
  assert(auth.includes("['moderator', 'admin', 'super_admin']"), 'staff guard should allow moderator plus admin roles');
  assert(authFlow.includes("moderator: '/staff-dashboard'"), 'moderator dashboard redirect should go to staff dashboard');
  assert(authFlow.includes("return 'moderator'"), 'staff/moderator audience normalization should exist');

  assert(sanitizer.includes("'/staff-dashboard'"), 'staff dashboard must be protected from anonymous HTML');
  assert(sanitizer.includes("'Staff Operations Dashboard'"), 'public sanitizer must forbid staff dashboard title');
  assert(sanitizer.includes("role === 'moderator'"), 'moderator role must be allowed for staff dashboard only');

  assert(server.includes("const staffRoutes = require('./routes/staff')"), 'server should import staff routes');
  assert(server.includes("app.use('/api/staff', staffRoutes)"), 'server should mount /api/staff');
  assert(server.includes('renderPublicHtml(req.originalUrl || req.url || req.path)'), 'server should render /login?next=/staff-dashboard with the staff account panel mode');
  assert(server.includes('staff-operations-dashboard-20260620a'), 'server should bump the public JS asset version for staff dashboard browsers');
  assert(server.includes('staff-source-monitor-guide-20260630'), 'server should cache-bust the staff source monitor guide');
  assert(server.includes('staff-dashboard-auth-race-20260701'), 'server should cache-bust the staff dashboard auth race fix');

  assert(staffRoutes.includes("router.get('/dashboard'"), 'staff dashboard API route should exist');
  assert(staffRoutes.includes("router.patch('/profile'"), 'staff profile/settings save API should exist');
  assert(staffRoutes.includes("router.get('/properties/:id/preview'"), 'staff listing preview API should exist');
  assert(staffRoutes.includes("router.patch('/properties/:id/review'"), 'staff listing preview save API should exist');
  assert(staffRoutes.includes("router.post('/source-intake/exact-social/import'"), 'staff social source import API should exist');
  assert(staffRoutes.includes("router.post('/source-intake/social-sweep'"), 'staff social sweep API should exist');
  assert(staffRoutes.includes('STAFF_EXACT_SOCIAL_IMPORT_LIMIT = 500'), 'staff exact social import should cap batches at 500');
  assert(staffRoutes.includes('Paste at least one exact social post/video URL'), 'staff source import should reject source pages/hashtags without exact URLs');
  assert(staffRoutes.includes('metadata_skipped_for_large_batch'), 'staff source import should report large-batch metadata skips');
  assert(staffRoutes.includes("router.patch('/leads/:id'"), 'staff lead update API route should exist');
  assert(staffRoutes.includes("router.patch('/advertising/inquiries/:id'"), 'staff advertising update API route should exist');
  assert(staffRoutes.includes("router.post('/assistant/query'"), 'staff AI assistant route should exist');
  assert(staffRoutes.includes('staff_contact_export_v1'), 'staff AI should expose controlled contact export answers');
  assert(staffRoutes.includes('buildAutomatedListingReview'), 'staff listing preview should return the same automated review checks as King review');
  assert(staffRoutes.includes('matchAll(/\\b(?:in|around|near|at)'), 'staff AI should parse the final real location phrase instead of greedy "for people" text');
  assert(staffRoutes.includes('(\\d{1,3})\\s+(?:phone|phones|number|numbers|contact|contacts|rows|people)'), 'staff AI contact export should honor "give me 5 phone numbers" style limits');
  assert(staffRoutes.includes('normalizeReviewLocationHierarchy'), 'staff listing edits should validate Uganda location hierarchy');
  assert(staffRoutes.includes('districtForKnownArea'), 'staff listing edits should catch Nansana/Wakiso and Masindi/Masindi style hierarchy bugs');
  assert(staffRoutes.includes('map_pin_confirmed'), 'staff preview save should persist confirmed map pins from the King review panel');
  assert(staffRoutes.includes('nearest_university'), 'staff preview save should persist student accommodation fields from the King review panel');
  assert(staffRoutes.includes('amenities = $'), 'staff preview save should persist amenities from extracted source facts');
  assert(staffRoutes.includes('staff_activity_logs'), 'staff routes should write staff activity logs');
  assert(staffRoutes.includes('Moderators can only assign a lead to themselves'), 'lead assignment should be staff self-service only');

  assert(adminRoutes.includes("router.get('/staff'"), 'King dashboard should list moderator staff users');
  assert(adminRoutes.includes("router.post('/staff/bootstrap-five'"), 'King dashboard should bootstrap five moderator accounts');
  assert(adminRoutes.includes("router.patch('/staff/:id'"), 'King dashboard should edit moderator accounts');
  assert(adminRoutes.includes("router.post('/staff/:id/password-reset'"), 'King dashboard should reset moderator passwords');
  assert(adminRoutes.includes("'moderator'"), 'admin routes should recognize moderator role');

  assert(propertyRoutes.includes('requireListingModerationAccess'), 'property status route should use listing moderation access');
  assert(propertyRoutes.includes("actorRole === 'moderator'"), 'moderator-specific publish restrictions should exist');
  assert(propertyRoutes.includes('Found-online staff approval requires source review confirmation'), 'moderator found-online approval should require explicit source review confirmation');
  assert(propertyRoutes.includes('found_online_source_reviewed'), 'found-online approvals should persist source review confirmation');
  assert(propertyRoutes.includes('staff_listing_approved'), 'moderator approvals should be logged');

  assert(html.includes('id="page-staff-dashboard"'), 'staff dashboard page should be in the product');
  assert(html.includes('id="staff-settings-panel"'), 'staff dashboard should expose staff settings and payout details');
  assert(html.includes('id="staff-stat-total"'), 'staff dashboard should show live property count');
  assert(html.includes('Live Properties'), 'staff dashboard should label public inventory as live properties');
  assert(html.includes('onclick="staffJumpToDesk(\'leads\')"'), 'open leads metric should jump to lead actions');
  assert(html.includes('id="staff-review-panel"'), 'staff dashboard should expose review action panel target');
  assert(html.includes('id="staff-source-panel"'), 'staff dashboard should expose source action panel target');
  assert(html.includes('id="staff-leads-panel"'), 'staff dashboard should expose lead action panel target');
  assert(html.includes('id="staff-advertising-panel"'), 'staff dashboard should expose advertising action panel target');
  assert(html.includes('id="staff-whatsapp-panel"'), 'staff dashboard should expose WhatsApp action panel target');
  assert(html.includes('id="staff-bank-panel"'), 'staff dashboard should expose bank lead action panel target');
  assert(html.includes('id="staff-stat-duplicates"'), 'staff dashboard should show duplicate risk count');
  assert(html.includes('id="staff-source-quick-paste"'), 'staff dashboard should expose source quick paste');
  assert(html.includes('id="staff-source-monitor-card"'), 'staff dashboard should expose the continuous monitor process');
  assert(html.includes('id="staff-source-monitor-commands"'), 'staff dashboard should show trigger commands for the monitor');
  assert(html.includes('id="staff-source-sweep-youtube-mode"'), 'staff dashboard should let staff choose safe/broad YouTube sweep mode');
  assert(html.includes('staff-source-monitor-guide-20260630'), 'index should cache-bust the staff source monitor guide');
  assert(html.includes('staff-dashboard-auth-race-20260701'), 'index should cache-bust the staff dashboard auth race fix');
  assert(html.includes('staff-dashboard-hydration-20260701'), 'index should cache-bust the staff dashboard hydration guard');
  assert(html.includes('staff-dashboard-retry-20260701'), 'index should cache-bust the staff dashboard transient retry guard');
  assert(html.includes('public-summary-stale-session-fix-20260701'), 'index should cache-bust stale-session public summary recovery');
  assert(html.includes('staff-source-intake-20260701'), 'index should cache-bust staff source intake updates');
  assert(html.includes('staff-active-dashboard-20260701'), 'index should cache-bust active-dashboard hydration fixes');
  assert(html.includes('id="staff-bank-leads-list"'), 'staff dashboard should expose bank/mortgage leads');
  assert(html.includes('id="staff-review-queue"'), 'staff moderation queue container should exist');
  assert(html.includes('id="staff-ai-question"'), 'staff AI assistant UI should exist');
  assert(html.includes('id="admin-staff-control"'), 'King dashboard should include staff operations control panel');
  assert(html.includes('adminBootstrapStaffAccounts()'), 'King dashboard should expose five-account bootstrap action');
  assert(app.includes('"staff-dashboard": "/staff-dashboard"'), 'frontend route map should include staff dashboard');
  assert(app.includes('renderStaffDashboard'), 'frontend should render staff dashboard');
  assert(app.includes('renderAdminStaffControl'), 'King dashboard should render staff account control');
  assert(app.includes('/api/admin/staff/bootstrap-five'), 'King dashboard should call staff bootstrap API');
  assert(app.includes('/api/staff/dashboard'), 'frontend should fetch staff dashboard API');
  assert(app.includes('staffDashboardRenderSeq'), 'staff dashboard should ignore stale first-load API responses');
  assert(app.includes('staffDashboardHasLiveData'), 'staff dashboard should not clear live data after a stale auth failure');
  assert(app.includes('staffDashboardAuthRetryCount'), 'staff dashboard should quietly retry transient first-load auth failures');
  assert(app.includes('!authState?.token'), 'staff dashboard should not open the loaded shell without a real auth token');
  assert(app.includes('staleAuthRequest'), 'staff dashboard should suppress stale sign-in-required toasts');
  assert(app.includes('stillSignedInStaff'), 'staff dashboard should not show false sign-in-required toasts while staff auth is active');
  assert(app.includes('function isAuthSessionFailure'), 'frontend should detect genuinely expired/invalid auth sessions');
  assert(app.includes('Staff dashboard session expired. Please sign in again.'), 'real expired staff sessions should return to sign-in instead of showing zeroed panels');
  assert(app.includes('function setStaffDashboardLoadingState'), 'staff dashboard should show loading instead of zero stats before hydration');
  assert(app.includes('transientStaffRequest'), 'staff dashboard should retry transient first-load API failures');
  assert(app.includes('Staff dashboard is still loading. Retrying live data...'), 'transient staff API failures should keep retrying without painting failed zero panels');
  assert(app.includes('function renderActiveAuthDashboard'), 'auth persistence should not render every hidden dashboard during sign-in');
  assert(app.includes('currentPage !== expectedAuthDashboard'), 'auth persistence should not rerender a previous dashboard for the wrong signed-in role');
  assert(app.includes('function canSyncSavedPropertiesForCurrentUser'), 'staff/admin sign-in should skip property-seeker saved-list sync');
  assert(app.includes('if (finderMode !== "finder")'), 'finder dashboard should not hydrate for staff/admin users');
  assert(app.includes('renderSaved();\n  renderActiveAuthDashboard();'), 'global rendering should only hydrate the active auth dashboard');
  assert(app.includes('async function refreshAuthSession()'), 'frontend should refresh auth sessions explicitly');
  assert(app.includes('const tokenAtStart = authState.token'), 'auth refresh should capture the token it started with');
  assert(app.includes('if (tokenAtStart !== authState?.token) return;'), 'stale auth refreshes should not clear a newer staff login session');
  assert(!app.includes('applyAuthUi();\n  renderFinderDashboard();'), 'sign-in should not fire every dashboard API at once');
  assert(!app.includes('renderSaved();\n  renderFinderDashboard();'), 'global render should not fire the hidden finder dashboard for staff users');
  assert(!app.includes('showPage("staff-dashboard");\n    renderStaffDashboard();'), 'staff sign-in should not double-render the staff dashboard');
  assert(!app.includes('showPage("staff-dashboard", { history: false, source: "deep_link" });\n      renderStaffDashboard();'), 'staff deep link should not double-render the staff dashboard');
  assert(app.includes('staff-source-monitor-cadence'), 'frontend should render source monitor cadence');
  assert(app.includes('youtube_job_mode: youtubeJobMode'), 'frontend should send staff-selected YouTube job mode');
  assert(app.includes('/api/staff/assistant/query'), 'frontend should call staff assistant API');
  assert(app.includes('/api/staff/profile'), 'frontend should save staff settings');
  assert(app.includes('staffJumpToDesk'), 'staff stats should be clickable action jumps');
  assert(app.includes('data.summary?.listings?.live'), 'staff dashboard total stat should use live public listings');
  assert(app.includes('staffWhatsappBridgeCopy'), 'staff dashboard should render hosted WhatsApp bridge status');
  assert(app.includes('staffUseSourcePreset'), 'staff source intake should expose search presets');
  assert(app.includes('staffSourceImportUrlCount'), 'staff source import should switch large batches to fast metadata mode');
  assert(app.includes('fetch_oembed: metadataEnabled'), 'staff source import should skip external metadata fetches on large batches');
  assert(app.includes('metadata_skipped_for_large_batch'), 'staff source import should explain when metadata was skipped for speed');
  assert(app.includes('setStaffTrainingTab'), 'staff training should render one focused workflow at a time');
  assert(app.includes('copyStaffTrainingScript'), 'staff scripts should be copyable');
  assert(app.includes('/api/staff/properties/${encodeURIComponent(propertyId)}/preview'), 'frontend should open staff listing preview before approval');
  assert(app.includes('adminReviewListingEditPanel(preview)'), 'staff preview should reuse the King review edit panel');
  assert(app.includes('collectAdminReviewListingPatch()'), 'staff preview save should collect the King review edit panel fields');
  assert(app.includes('initAdminReviewLocationMap(preview)'), 'staff preview should render the same King review map pin control');
  assert(app.includes('const location = preview.location_review || {}'), 'staff preview should define location guardrail data before rendering warnings');
  assert(app.includes('openStaffOwnerStatusWhatsApp'), 'staff decisions should open owner WhatsApp notification drafts');
  assert(app.includes('function staffBuildReviewWarningOverrides'), 'staff approval should build moderator warning overrides from preview checks');
  assert(app.includes('saveStaffListingPreview(propertyId, { prepareApproval: true })'), 'staff approval should save preview facts with approval overrides before publishing');
  assert(app.includes('warning_overrides: warningOverrides'), 'staff approval status call should submit warning overrides to the live publish API');
  assert(app.includes('const foundOnlineApproval = typeof adminIsSourcedInventoryCandidate === "function" && adminIsSourcedInventoryCandidate(adminActiveReview)'), 'staff approval should detect found-online rows before publishing');
  assert(app.includes('staff_source_reviewed: true'), 'staff found-online approval should confirm source review to the backend');
  assert(app.includes('buildAdminApprovalWhatsAppMessage(listing)'), 'staff approval WhatsApp modal should have the same approval-message fallback as King moderation');
  assert(app.includes('Approve live after preview'), 'frontend should require preview before live approval');
  assert(app.includes('/api/staff/source-intake/exact-social/import'), 'frontend should call staff source intake import');
  assert(app.includes('/api/staff/source-intake/social-sweep'), 'frontend should call staff source sweep');
  assert(app.includes('Copy CSV'), 'staff AI should render contact CSV copy control');
  assert(app.includes('function preferredAudienceForResolvedUser'), 'generic account drawer sign-in should resolve staff role from returned user');
  assert(app.includes('return derivePortalMode(user, "")'), 'finder drawer sign-in must not force moderator accounts into finder dashboard');
  assert(app.includes('const isModerator = accountAccessDrawerAudience === "moderator"'), 'staff sign-in drawer should treat moderator as an internal role');
  assert(app.includes('Sign in with your staff moderator account'), 'staff sign-in drawer should explain moderator access');
  assert(app.includes('staffModerateListing'), 'frontend should expose moderation action');
  assert(app.includes('moderator email or +256'), 'staff sign-in copy should be present');
  assert(staffRoutes.includes('STAFF_SOURCE_PRESETS'), 'staff API should return local source-search presets');
  assert(staffRoutes.includes('whatsapp_web_bridge_clients'), 'staff API should include hosted WhatsApp bridge heartbeat proof');
  assert(staffRoutes.includes('STAFF_REMOVED_STATUSES'), 'staff API should hide rejected/deleted/test rows from staff queues');
  assert(staffRoutes.includes('publicCustomerVisiblePropertyWhere'), 'staff live counts should use the same customer-visible suppression as public property APIs');
  assert(staffRoutes.includes('PUBLIC_SUPPRESSED_LISTING_MARKERS'), 'staff live counts should suppress soft-launch and QA records');
  assert(staffRoutes.includes("COUNT(*) FILTER (WHERE ${publicCustomerVisiblePropertyWhere('p')})::int AS live"), 'staff live property count must not include public-suppressed records');
  assert(staffRoutes.includes('source_presets: STAFF_SOURCE_PRESETS'), 'staff dashboard payload should include source presets');
  assert(staffRoutes.includes('monitor: staffSourceMonitorGuide()'), 'staff dashboard payload should include continuous source monitor guidance');
  assert(staffRoutes.includes('PROPERTY_SOURCE_REGISTRY_TARGET_COUNT'), 'staff source monitor guide should show the 60,000 source target');
  assert(staffRoutes.includes('continuous_social_monitor_run'), 'staff source monitor guide should expose the audit action for confirmed runs');
  assert(staffRoutes.includes('youtubeJobMode'), 'staff social sweep endpoint should pass through the YouTube job mode');
  assert(staffRoutes.includes("whatsapp: { ...whatsappSummary, bridge: whatsappBridge }"), 'staff dashboard payload should expose WhatsApp bridge status');
  assert(staffRoutes.includes('FROM whatsapp_messages m'), 'staff dashboard and assistant should fall back to raw WhatsApp messages');
  assert(staffRoutes.includes('warning_overrides: safeJsonObject(req.body.warning_overrides, {})'), 'staff review save API should accept moderator warning overrides');
  assert(staffRoutes.includes('extraPatch.review_warning_overrides = warningOverrides'), 'staff review save should persist warning overrides for the live publish route');
  assert(staffRoutes.includes('staff_review_warning_overrides_by'), 'staff review save should audit who recorded warning overrides');
  assert(staffRoutes.includes('checklist_items: automatedReview.checks'), 'staff preview should expose automated warning rows for moderator override keys');

  console.log('staff-moderator-workbench tests passed');
}

run();
