const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');

function run() {
  const migration = read('db/migrations/064_staff_moderator_workbench.sql');
  const auth = read('middleware/auth.js');
  const authFlow = read('services/authFlowService.js');
  const sanitizer = read('services/publicHtmlSanitizer.js');
  const server = read('server.js');
  const staffRoutes = read('routes/staff.js');
  const staffReviewQueuePerfMigration = read('db/migrations/067_staff_review_queue_performance.sql');
  const staffBulkModerationMigration = read('db/migrations/068_staff_bulk_moderation_performance.sql');
  const suppressedSourcesMigration = read('db/migrations/069_suppressed_sources_registry.sql');
  const studentSupplyBackfillMigration = read('db/migrations/070_student_supply_gate_backfill.sql');
  const adminRoutes = read('routes/admin.js');
  const propertyRoutes = read('routes/properties.js');
  const sourceQuality = read('utils/sourceContentQuality.js');
  const sourceUrlNormalization = read('utils/sourceUrlNormalization.js');
  const suppressedSourceService = read('services/suppressedSourceService.js');
  const socialSearchService = read('services/socialSearchSourcedListingsService.js');
  const app = read('assets/makaug-app.js');
  const html = read('index.html');
  const staffApproveStart = app.indexOf('async function staffApprovePreviewListing');
  const staffApproveEnd = app.indexOf('async function staffRejectPreviewListing');
  const staffApproveBody = staffApproveStart >= 0 && staffApproveEnd > staffApproveStart
    ? app.slice(staffApproveStart, staffApproveEnd)
    : '';
  const staffPanelsStart = staffRoutes.indexOf('async function dashboardPanelsPayload');
  const staffPanelsEnd = staffRoutes.indexOf('function normalizeStaffListingPatch', staffPanelsStart);
  const staffPanelsBody = staffPanelsStart >= 0 && staffPanelsEnd > staffPanelsStart
    ? staffRoutes.slice(staffPanelsStart, staffPanelsEnd)
    : '';

  assert(migration.includes("'moderator'"), 'users role check must include moderator');
  assert(migration.includes('CREATE TABLE IF NOT EXISTS staff_activity_logs'), 'staff activity log table must exist');
  assert(migration.includes('assigned_to_user_id'), 'lead/ad ownership should be assignable to staff users');

  assert(auth.includes('requireStaffAccess'), 'auth middleware must export staff guard');
  assert(auth.includes('requireListingModerationAccess'), 'property publish route must use restricted moderation guard');
  assert(auth.includes("['moderator', 'admin', 'super_admin']"), 'staff guard should allow moderator plus admin roles');
  assert(authFlow.includes("moderator: '/staff-dashboard'"), 'moderator dashboard redirect should go to staff dashboard');
  assert(authFlow.includes("return 'moderator'"), 'staff/moderator audience normalization should exist');

  assert(sanitizer.includes("'/staff-dashboard'"), 'staff dashboard must be protected from anonymous HTML');
  assert(sanitizer.includes("'Staff Operations Dashboard'"), 'public sanitizer must forbid staff dashboard title');
  assert(sanitizer.includes("role === 'moderator'"), 'moderator role must be allowed for staff dashboard only');

  assert(server.includes("const staffRoutes = require('./routes/staff')"), 'server should import staff routes');
  assert(server.includes("app.use('/api/staff', staffRoutes)"), 'server should mount /api/staff');
  assert(server.includes('renderPublicHtml(req.originalUrl || req.url || req.path)'), 'server should render /login?next=/staff-dashboard with the staff account panel mode');
  assert(server.includes('staff-operations-dashboard-20260620a'), 'server should bump the public JS asset version for staff dashboard browsers');
  assert(server.includes('staff-source-monitor-guide-20260630'), 'server should cache-bust the staff source monitor guide');
  assert(server.includes('staff-dashboard-auth-race-20260701'), 'server should cache-bust the staff dashboard auth race fix');

  assert(staffRoutes.includes("router.get('/dashboard'"), 'staff dashboard API route should exist');
  assert(staffRoutes.includes("router.get('/properties/review-queue'"), 'staff review queue API route should exist instead of 404ing');
  assert(staffRoutes.includes("router.post('/properties/bulk-review'"), 'staff bulk review API route should exist for high-volume moderation');
  assert(staffRoutes.includes("router.post('/properties/bulk-reject'"), 'staff bulk reject API route should exist for clear-junk suppression');
  assert(staffRoutes.includes("router.patch('/profile'"), 'staff profile/settings save API should exist');
  assert(staffRoutes.includes("router.get('/properties/:id/preview'"), 'staff listing preview API should exist');
  assert(staffRoutes.includes('brokerReviewWhere'), 'staff dashboard should classify broker-submitted review listings');
  assert(staffRoutes.includes('broker_pending_review'), 'staff dashboard summary should count broker listings separately');
  assert(staffRoutes.includes('broker_review_queue'), 'staff dashboard API should return a dedicated broker review queue');
  assert(staffRoutes.includes("router.patch('/properties/:id/review'"), 'staff listing preview save API should exist');
  assert(staffRoutes.includes("router.post('/source-intake/exact-social/import'"), 'staff social source import API should exist');
  assert(staffRoutes.includes("router.post('/source-intake/social-sweep'"), 'staff social sweep API should exist');
  assert(staffRoutes.includes('STAFF_EXACT_SOCIAL_IMPORT_LIMIT = 500'), 'staff exact social import should cap batches at 500');
  assert(staffRoutes.includes('Paste at least one exact social post/video URL'), 'staff source import should reject source pages/hashtags without exact URLs');
  assert(staffRoutes.includes('metadata_skipped_for_large_batch'), 'staff source import should report large-batch metadata skips');
  assert(staffRoutes.includes("router.patch('/leads/:id'"), 'staff lead update API route should exist');
  assert(staffRoutes.includes("router.patch('/advertising/inquiries/:id'"), 'staff advertising update API route should exist');
  assert(staffRoutes.includes("router.post('/assistant/query'"), 'staff AI assistant route should exist');
  assert(staffRoutes.includes('staff_contact_export_v1'), 'staff AI should expose controlled contact export answers');
  assert(staffRoutes.includes('buildAutomatedListingReview'), 'staff listing preview should return the same automated review checks as King review');
  assert(staffRoutes.includes('matchAll(/\\b(?:in|around|near|at)'), 'staff AI should parse the final real location phrase instead of greedy "for people" text');
  assert(staffRoutes.includes('(\\d{1,3})\\s+(?:phone|phones|number|numbers|contact|contacts|rows|people)'), 'staff AI contact export should honor "give me 5 phone numbers" style limits');
  assert(staffRoutes.includes('normalizeReviewLocationHierarchy'), 'staff listing edits should validate Uganda location hierarchy');
  assert(staffRoutes.includes('districtForKnownArea'), 'staff listing edits should catch Nansana/Wakiso and Masindi/Masindi style hierarchy bugs');
  assert(staffRoutes.includes('map_pin_confirmed'), 'staff preview save should persist confirmed map pins from the King review panel');
  assert(staffRoutes.includes('nearest_university'), 'staff preview save should persist student accommodation fields from the King review panel');
  assert(staffRoutes.includes('amenities = $'), 'staff preview save should persist amenities from extracted source facts');
  assert(staffRoutes.includes('staff_activity_logs'), 'staff routes should write staff activity logs');
  assert(staffRoutes.includes('Moderators can only assign a lead to themselves'), 'lead assignment should be staff self-service only');

  assert(adminRoutes.includes("router.get('/staff'"), 'King dashboard should list moderator staff users');
  assert(adminRoutes.includes("router.post('/staff/bootstrap-five'"), 'King dashboard should bootstrap five moderator accounts');
  assert(adminRoutes.includes("router.patch('/staff/:id'"), 'King dashboard should edit moderator accounts');
  assert(adminRoutes.includes("router.post('/staff/:id/password-reset'"), 'King dashboard should reset moderator passwords');
  assert(adminRoutes.includes("'moderator'"), 'admin routes should recognize moderator role');

  assert(propertyRoutes.includes('requireListingModerationAccess'), 'property status route should use listing moderation access');
  assert(propertyRoutes.includes("actorRole === 'moderator'"), 'moderator-specific publish restrictions should exist');
  assert(propertyRoutes.includes('Found-online staff approval requires source review confirmation'), 'moderator found-online approval should require explicit source review confirmation');
  assert(propertyRoutes.includes('found_online_source_reviewed'), 'found-online approvals should persist source review confirmation');
  assert(propertyRoutes.includes('staff_listing_approved'), 'moderator approvals should be logged');
  assert(propertyRoutes.includes('canSkipAutomatedReviewForSourcedOverride'), 'source-reviewed found-online approvals should skip the heavy automated review on the write path');
  assert(propertyRoutes.includes('Found-online source override used saved checklist data for fast moderation write.'), 'fast found-online approval path should be visible in warnings');
  assert(propertyRoutes.includes('const fastAdminRender = parseBooleanLike'), 'status route should separate fast admin rendering from notification mode');
  assert(propertyRoutes.includes('applyStatusListingPatchBeforeModeration'), 'status route should apply edited listing facts before approval/rejection');
  assert(propertyRoutes.includes('listing_facts_updated_with_status'), 'status route should audit listing fact edits made during moderation status changes');
  assert(propertyRoutes.includes('statusListingPatchFromBody(req.body)'), 'status route should read listing patches from the approval payload');
  assert(propertyRoutes.includes('Deferred fast moderation audit failed'), 'fast staff moderation should defer non-critical audit follow-up after the status update');
  assert(propertyRoutes.includes('return res.json(buildStatusResponse(fastAlertMatching))'), 'fast staff moderation should respond before deferred audit/search follow-up finishes');

  assert(html.includes('id="page-staff-dashboard"'), 'staff dashboard page should be in the product');
  assert(html.includes('id="staff-settings-panel"'), 'staff dashboard should expose staff settings and payout details');
  assert(html.includes('id="staff-stat-total"'), 'staff dashboard should show live property count');
  assert(html.includes('Live Properties'), 'staff dashboard should label public inventory as live properties');
  assert(html.includes('onclick="staffJumpToDesk(\'leads\')"'), 'open leads metric should jump to lead actions');
  assert(html.includes('id="staff-review-panel"'), 'staff dashboard should expose review action panel target');
  assert(html.includes('id="staff-source-panel"'), 'staff dashboard should expose source action panel target');
  assert(html.includes('id="staff-leads-panel"'), 'staff dashboard should expose lead action panel target');
  assert(html.includes('id="staff-advertising-panel"'), 'staff dashboard should expose advertising action panel target');
  assert(html.includes('id="staff-whatsapp-panel"'), 'staff dashboard should expose WhatsApp action panel target');
  assert(html.includes('id="staff-bank-panel"'), 'staff dashboard should expose bank lead action panel target');
  assert(html.includes('id="staff-stat-duplicates"'), 'staff dashboard should show duplicate risk count');
  assert(html.includes('id="staff-source-quick-paste"'), 'staff dashboard should expose source quick paste');
  assert(html.includes('id="staff-source-monitor-card"'), 'staff dashboard should expose the continuous monitor process');
  assert(html.includes('id="staff-source-monitor-commands"'), 'staff dashboard should show trigger commands for the monitor');
  assert(html.includes('id="staff-source-sweep-youtube-mode"'), 'staff dashboard should let staff choose safe/broad YouTube sweep mode');
  assert(html.includes('staff-source-monitor-guide-20260630'), 'index should cache-bust the staff source monitor guide');
  assert(html.includes('staff-dashboard-auth-race-20260701'), 'index should cache-bust the staff dashboard auth race fix');
  assert(html.includes('staff-dashboard-hydration-20260701'), 'index should cache-bust the staff dashboard hydration guard');
  assert(html.includes('staff-dashboard-retry-20260701'), 'index should cache-bust the staff dashboard transient retry guard');
  assert(html.includes('public-summary-stale-session-fix-20260701'), 'index should cache-bust stale-session public summary recovery');
  assert(html.includes('staff-source-intake-20260701'), 'index should cache-bust staff source intake updates');
  assert(html.includes('staff-active-dashboard-20260701'), 'index should cache-bust active-dashboard hydration fixes');
  assert(html.includes('staff-fast-dashboard-20260701'), 'index should cache-bust fast staff dashboard hydration');
  assert(html.includes('king-api-fallback-staff-session-20260703'), 'index should cache-bust King API-key fallback for staff-session edge');
  assert(html.includes('id="staff-bank-leads-list"'), 'staff dashboard should expose bank/mortgage leads');
  assert(html.includes('id="staff-review-queue"'), 'staff moderation queue container should exist');
  assert(html.includes('id="staff-broker-review-queue"'), 'staff dashboard should include a broker listings review queue');
  assert(html.includes('id="staff-stat-broker-pending"'), 'staff dashboard should include a broker listing counter');
  assert(html.includes('id="staff-ai-question"'), 'staff AI assistant UI should exist');
  assert(html.includes('id="admin-staff-control"'), 'King dashboard should include staff operations control panel');
  assert(html.includes('adminBootstrapStaffAccounts()'), 'King dashboard should expose five-account bootstrap action');
  assert(app.includes('"staff-dashboard": "/staff-dashboard"'), 'frontend route map should include staff dashboard');
  assert(app.includes('renderStaffDashboard'), 'frontend should render staff dashboard');
  assert(app.includes('renderStaffBrokerReviewQueue'), 'frontend should render the broker review queue separately');
  assert(app.includes('adminIsBrokerSubmissionListing'), 'frontend should identify broker-submitted review rows');
  assert(app.includes('adminPendingQueueFilterButton("broker", "Broker", counts.broker)'), 'King review queue should expose a broker filter');
  assert(app.includes('renderAdminStaffControl'), 'King dashboard should render staff account control');
  assert(app.includes('/api/admin/staff/bootstrap-five'), 'King dashboard should call staff bootstrap API');
  assert(app.includes('saveAdminGateApiKeyAndRefresh'), 'King dashboard should let a stale admin shell reconnect with ADMIN_API_KEY fallback');
  assert(app.includes('Role: Admin API Key • live backend'), 'King dashboard API-key fallback should render live backend status');
  assert(app.includes('admin_api_key_fallback'), 'King dashboard should show the API-key reconnect gate when a signed-in non-admin opens /admin');
  assert(server.includes('shouldServeAdminShellForApiKeyFallback'), 'server should not hard-403 the King shell before the API-key fallback can render');
  assert(server.includes('X-makaug-Admin-Api-Key-Fallback'), 'server should mark the signed-in non-admin King shell fallback response');
  assert(app.includes('/api/staff/dashboard'), 'frontend should fetch staff dashboard API');
  assert(app.includes('staffDashboardRenderSeq'), 'staff dashboard should ignore stale first-load API responses');
  assert(app.includes('staffDashboardHasLiveData'), 'staff dashboard should not clear live data after a stale auth failure');
  assert(app.includes('staffDashboardAuthRetryCount'), 'staff dashboard should quietly retry transient first-load auth failures');
  assert(app.includes('!authState?.token'), 'staff dashboard should not open the loaded shell without a real auth token');
  assert(app.includes('staleAuthRequest'), 'staff dashboard should suppress stale sign-in-required toasts');
  assert(app.includes('stillSignedInStaff'), 'staff dashboard should not show false sign-in-required toasts while staff auth is active');
  assert(app.includes('function isAuthSessionFailure'), 'frontend should detect genuinely expired/invalid auth sessions');
  assert(app.includes('Staff dashboard session expired. Please sign in again.'), 'real expired staff sessions should return to sign-in instead of showing zeroed panels');
  assert(app.includes('function setStaffDashboardLoadingState'), 'staff dashboard should show loading instead of zero stats before hydration');
  assert(app.includes('transientStaffRequest'), 'staff dashboard should retry transient first-load API failures');
  assert(app.includes('Staff dashboard is still loading. Retrying live data...'), 'transient staff API failures should keep retrying without painting failed zero panels');
  assert(app.includes('function renderActiveAuthDashboard'), 'auth persistence should not render every hidden dashboard during sign-in');
  assert(app.includes('currentPage !== expectedAuthDashboard'), 'auth persistence should not rerender a previous dashboard for the wrong signed-in role');
  assert(app.includes('function canSyncSavedPropertiesForCurrentUser'), 'staff/admin sign-in should skip property-seeker saved-list sync');
  assert(app.includes('if (finderMode !== "finder")'), 'finder dashboard should not hydrate for staff/admin users');
  assert(app.includes('renderSaved();\n  renderActiveAuthDashboard();'), 'global rendering should only hydrate the active auth dashboard');
  assert(app.includes('/api/staff/dashboard?fast=1'), 'staff dashboard should first request the fast payload');
  assert(app.includes('function hydrateStaffDashboardPanels'), 'staff dashboard should hydrate heavy panels in the background');
  assert(staffRoutes.includes('function dashboardFastPayload'), 'staff API should expose a fast dashboard payload');
  assert(staffRoutes.includes('STAFF_FAST_DASHBOARD_CACHE_TTL_MS'), 'fast staff dashboard should cache expensive first-paint counts briefly');
  assert(staffRoutes.includes('function clearStaffFastDashboardCache'), 'staff inventory changes should invalidate the fast dashboard cache');
  assert(staffRoutes.includes("deferred_dashboard_endpoint: '/api/staff/dashboard?panels=1'"), 'fast dashboard payload should point to deferred panels');
  assert(staffRoutes.includes('sourceQualitySuppressedFlagSql'), 'staff dashboard should hide stored non-listing construction/tutorial source rows without full regex scans');
  assert(staffRoutes.includes('function sourceQualitySuppressedFlagSql'), 'staff dashboard counts should use a cheap stored source-quality flag');
  assert(staffRoutes.includes('function staffActiveReviewRows'), 'staff dashboard should filter legacy suppressed rows in Node after a bounded over-fetch');
  assert(staffRoutes.includes('function staffModerationPanelRows'), 'staff moderation panel should not re-run fuzzy source-quality filtering after SQL count parity');
  assert(staffRoutes.includes("process.env.STAFF_DASHBOARD_PANEL_QUERY_TIMEOUT_MS || '5000'"), 'staff panels endpoint should allow the live review queue query enough time to return rows');
  assert(staffRoutes.includes('async function safeRowsResult'), 'staff panel row queries should report timeout/error metadata instead of pretending empty');
  assert(staffReviewQueuePerfMigration.includes('idx_properties_staff_active_review_queue_order'), 'staff review queue needs a dedicated ordered partial index');
  assert(staffReviewQueuePerfMigration.includes('ANALYZE properties'), 'staff review queue performance migration should refresh planner stats after creating the index');
  assert(staffBulkModerationMigration.includes('idx_properties_staff_active_review_unsuppressed_order'), 'staff paginated review queue should have an unsuppressed ordered partial index');
  assert(staffBulkModerationMigration.includes('idx_properties_staff_review_lower_title_created'), 'staff duplicate gate should have a lower-title lookup index');
  assert(staffBulkModerationMigration.includes('idx_properties_staff_review_source_url_created'), 'staff duplicate gate should have a source URL lookup index');
  assert(suppressedSourcesMigration.includes('CREATE TABLE IF NOT EXISTS suppressed_sources'), 'suppressed sources registry migration should create the table');
  assert(suppressedSourcesMigration.includes('idx_suppressed_sources_source_url_unique'), 'suppressed sources should have a unique source_url index');
  assert(studentSupplyBackfillMigration.includes("listing_type = 'students'"), 'student supply backfill should move clear hostel rows into the student category');
  assert(studentSupplyBackfillMigration.includes('student-supply-gate-20260711'), 'student supply backfill should stamp the marker version');
  assert(staffRoutes.includes('STAFF_DASHBOARD_QUEUE_SCAN_LIMIT'), 'staff dashboard should over-fetch a bounded queue window instead of regex scanning the full pending set');
  assert(staffRoutes.includes('STAFF_DASHBOARD_PANEL_QUERY_TIMEOUT_MS'), 'staff panels endpoint should use server-side DB timeouts so one slow query cannot 503 the panel bundle');
  assert(staffRoutes.includes('STAFF_REVIEW_QUEUE_QUERY_TIMEOUT_MS'), 'standalone staff review queue endpoint should be timeout bounded');
  assert(staffPanelsBody.includes('panelQueryOptions'), 'staff panels endpoint should pass timeout options into panel queries');
  assert(staffPanelsBody.includes('const [recentActivity, reviewResult, brokerReviewResult, sourceQueueRows]'), 'staff panels endpoint should include recent activity with moderation panel query metadata');
  assert(staffPanelsBody.includes('NULL::text AS primary_image_url'), 'staff panels moderation queue should skip image joins for fast first render');
  assert(!staffPanelsBody.includes('LEFT JOIN LATERAL'), 'staff panels endpoint should not run per-row image lateral joins');
  assert(staffPanelsBody.includes('staffModerationPanelRows(reviewResult.rows, queueLimit)'), 'staff panels endpoint should render SQL-parity rows directly instead of filtering them to zero in JS');
  assert(staffPanelsBody.includes('WITH panel_candidates AS MATERIALIZED'), 'staff panels endpoint should pre-scan ordered pending IDs through the review queue index');
  assert(staffPanelsBody.includes("WHERE NOT ${sourceQualitySuppressedFlagSql('p')}"), 'staff panels endpoint should apply JSON suppression only after the small indexed candidate scan');
  assert(staffPanelsBody.includes('review_queue_meta'), 'staff panels endpoint should expose review queue query metadata for false-empty protection');
  assert(staffPanelsBody.includes('query_ok: reviewResult.ok'), 'staff panels endpoint should expose whether the moderation queue query really succeeded');
  assert(staffPanelsBody.includes('empty_is_authoritative: reviewResult.ok'), 'empty moderation queue should only be authoritative after a successful row query');
  assert(staffRoutes.includes("count_filter: 'staff_active_pending_review'"), 'staff review queue endpoint should advertise the same active pending filter used by staff counts');
  assert(staffRoutes.includes("source_quality_filter: 'stored_suppression_flag_only'"), 'staff review queue endpoint should use the cheap stored source-quality flag');
  assert(staffRoutes.includes('WITH paged_review_queue AS MATERIALIZED'), 'staff paginated review queue should page through an indexed ID candidate set');
  assert(staffRoutes.includes("error: 'review_queue_query_failed'"), 'staff paginated review queue should not return false-empty rows after a timeout');
  assert(staffRoutes.includes('async function dashboardPanelsPayload'), 'staff panels endpoint should return a queue-first lightweight payload');
  assert(staffRoutes.includes('if (panels) return res.json({ ok: true, data: await dashboardPanelsPayload(req) });'), 'staff dashboard panels query should not call the full heavy dashboard payload');
  assert(staffRoutes.includes('source_quality_suppressed_pending'), 'staff dashboard should count hidden source-quality rows separately');
  assert(staffRoutes.includes('source_quality_suppressed'), 'staff source intake should expose source-quality suppression status');
  assert(staffRoutes.includes('FROM properties p\n       WHERE p.id <> $1'), 'staff duplicate preview query should use a property alias for source-quality filtering');
  assert(staffRoutes.includes("AND NOT ${sourceQualitySuppressedFlagSql('p')}"), 'staff duplicate preview query should hide stored source-quality suppressed rows without full regex scans');
  assert(app.includes('STAFF_DASHBOARD_PANEL_TIMEOUT_MS'), 'frontend should timeout stuck staff panel hydration requests');
  assert(app.includes('Staff dashboard panels'), 'staff panel timeout should clearly identify the stuck request');
  assert(app.includes('function mergeStaffDashboardPanelData'), 'frontend should merge queue-first panel payloads into existing fast dashboard data');
  assert(app.includes('function staffReviewQueueLoadingHtml'), 'frontend should not render a timed-out queue query as a genuine empty queue');
  assert(app.includes('Listing moderation rows are still catching up.'), 'staff queue timeout state should be explicit in the dashboard');
  assert(app.includes('expected_count: data.summary?.listings?.pending_review'), 'staff review queue renderer should compare rows against the live pending count');
  assert(app.includes('async function refreshAuthSession()'), 'frontend should refresh auth sessions explicitly');
  assert(app.includes('const tokenAtStart = authState.token'), 'auth refresh should capture the token it started with');
  assert(app.includes('if (tokenAtStart !== authState?.token) return;'), 'stale auth refreshes should not clear a newer staff login session');
  assert(!app.includes('applyAuthUi();\n  renderFinderDashboard();'), 'sign-in should not fire every dashboard API at once');
  assert(!app.includes('renderSaved();\n  renderFinderDashboard();'), 'global render should not fire the hidden finder dashboard for staff users');
  assert(!app.includes('showPage("staff-dashboard");\n    renderStaffDashboard();'), 'staff sign-in should not double-render the staff dashboard');
  assert(!app.includes('showPage("staff-dashboard", { history: false, source: "deep_link" });\n      renderStaffDashboard();'), 'staff deep link should not double-render the staff dashboard');
  assert(app.includes('staff-source-monitor-cadence'), 'frontend should render source monitor cadence');
  assert(app.includes('youtube_job_mode: youtubeJobMode'), 'frontend should send staff-selected YouTube job mode');
  assert(app.includes('/api/staff/assistant/query'), 'frontend should call staff assistant API');
  assert(app.includes('/api/staff/profile'), 'frontend should save staff settings');
  assert(app.includes('staffJumpToDesk'), 'staff stats should be clickable action jumps');
  assert(app.includes('data.summary?.listings?.live'), 'staff dashboard total stat should use live public listings');
  assert(app.includes('staffWhatsappBridgeCopy'), 'staff dashboard should render hosted WhatsApp bridge status');
  assert(app.includes('staffUseSourcePreset'), 'staff source intake should expose search presets');
  assert(app.includes('staffSourceImportUrlCount'), 'staff source import should switch large batches to fast metadata mode');
  assert(app.includes('fetch_oembed: metadataEnabled || tiktokOembedOnly'), 'staff source import should skip external metadata fetches on large non-TikTok batches while keeping TikTok oEmbed batches enriched');
  assert(app.includes('staffSourceImportIsTikTokOnlyBatch'), 'staff source import should detect TikTok-only exact video batches');
  assert(app.includes('staffImportTikTokVideos'), 'staff source quick paste should expose a TikTok oEmbed import action');
  assert(app.includes('tiktok_oembed_manual_import'), 'staff TikTok paste imports should explicitly request oEmbed caption enrichment');
  assert(html.includes('Import TikTok Videos'), 'staff source quick paste should render the TikTok import button');
  assert(html.includes('review-queue-list-count-parity-20260711'), 'index should cache-bust review queue list/count parity fix');
  assert(html.includes('staff-panels-review-queue-20260711'), 'index should cache-bust the real staff panels review queue fix');
  assert(html.includes('staff-panels-review-queue-rows-20260711'), 'index should cache-bust the staff panel row parity fix');
  assert(html.includes('staff-review-queue-performance-20260711'), 'index should cache-bust the staff review queue performance fix');
  assert(html.includes('staff-bulk-moderation-20260711'), 'index should cache-bust the staff bulk moderation infrastructure');
  assert(html.includes('staff-bulk-gate-tighten-20260711'), 'index should cache-bust the tightened staff bulk-review gates');
  assert(server.includes('staff-bulk-gate-tighten-20260711'), 'server should cache-bust the tightened staff bulk-review gates');
  assert(html.includes('staff-bulk-gate-tighten-v2-20260711'), 'index should cache-bust the second-pass staff bulk-review gates');
  assert(server.includes('staff-bulk-gate-tighten-v2-20260711'), 'server should cache-bust the second-pass staff bulk-review gates');
  assert(html.includes('staff-bulk-gate-positive-20260711'), 'index should cache-bust the positive staff bulk-review gate');
  assert(server.includes('staff-bulk-gate-positive-20260711'), 'server should cache-bust the positive staff bulk-review gate');
  assert(html.includes('staff-bulk-gate-round4-20260711'), 'index should cache-bust the round-four staff bulk-review gate');
  assert(server.includes('staff-bulk-gate-round4-20260711'), 'server should cache-bust the round-four staff bulk-review gate');
  assert(html.includes('staff-suppressed-sources-registry-20260711'), 'index should cache-bust the suppressed source registry');
  assert(server.includes('staff-suppressed-sources-registry-20260711'), 'server should cache-bust the suppressed source registry');
  assert(html.includes('student-supply-gate-20260711'), 'index should cache-bust the student supply gate');
  assert(server.includes('student-supply-gate-20260711'), 'server should cache-bust the student supply gate');
  assert(staffRoutes.includes('function staffBulkModerationDecision'), 'staff bulk review should gate each listing server-side');
  assert(staffRoutes.includes('STAFF_CLEAR_JUNK_REJECT_REASONS'), 'staff bulk reject should default to clear-junk reasons only');
  assert(staffRoutes.includes('upsertSuppressedSourceRows'), 'staff bulk reject should write rejected source URLs into the suppression registry');
  assert(staffRoutes.includes('normalizedStaffListingSourceUrl'), 'staff bulk reject should normalize source URLs before suppressing them');
  assert(sourceUrlNormalization.includes('function normalizeSourceUrl'), 'source URL normalizer should be shared across staff and intake paths');
  assert(sourceUrlNormalization.includes('https://www.tiktok.com/@${match[1].toLowerCase()}/video/${match[2]}'), 'source URL normalizer should canonicalize TikTok video URLs');
  assert(suppressedSourceService.includes('suppressedSourceRowsForUrls'), 'suppressed source service should expose import-time lookup');
  assert(suppressedSourceService.includes('upsertSuppressedSourceRows'), 'suppressed source service should expose transactional upsert');
  assert(staffRoutes.includes('UGANDA_DISTRICT_SET'), 'staff bulk review should require a canonical Uganda district before approval');
  assert(staffRoutes.includes('STAFF_UGANDA_BBOX'), 'staff bulk review should geofence coordinates to Uganda before approval');
  assert(staffRoutes.includes('staffCoordinatesInsideUganda'), 'staff bulk review should reject coordinates outside Uganda');
  assert(staffRoutes.includes('owerri') && staffRoutes.includes('certificate\\s+of\\s+occupancy'), 'staff bulk review should block second-pass Nigerian location/title tokens');
  assert(staffRoutes.includes('real\\s+estate\\s+ltd') && staffRoutes.includes('ai[- ]powered'), 'staff bulk review should block company, promo, and episode rows');
  assert(sourceQuality.includes('function sourcePositiveListingGateForRecord'), 'source quality should expose a positive Uganda-property listing classifier');
  assert(sourceQuality.includes('POSITIVE_PROPERTY_NOUN_PATTERN'), 'positive classifier should require a concrete property noun');
  assert(sourceQuality.includes('POSITIVE_LISTING_INTENT_WITH_NOUN_PATTERN'), 'positive classifier should require listing intent with a concrete property noun');
  assert(sourceQuality.includes('POSITIVE_PROPERTY_COUNT_PATTERN'), 'positive classifier should accept concrete bedroom, plot, or acre counts');
  assert(sourceQuality.includes('POSITIVE_NEWS_POLITICS_PATTERN'), 'positive classifier should block news and politics clips');
  assert(sourceQuality.includes('POSITIVE_VLOG_EVENT_PATTERN'), 'positive classifier should block vlogs, events, worship nights, and generic clips');
  assert(socialSearchService.includes('sourcePositiveListingGateForItem'), 'source intake should reuse the positive listing classifier');
  assert(socialSearchService.includes('positiveListingGate.ok'), 'source intake should require the positive classifier before queuing review rows');
  assert(socialSearchService.includes('positive_listing_gate_passed'), 'source intake should expose positive-gate status for source-review records');
  assert(socialSearchService.includes('suppressedSourceRowsForItems'), 'source intake should check rejected source URLs before queuing posts');
  assert(socialSearchService.includes("'skipped_suppressed'"), 'source intake should report suppressed URLs as skipped_suppressed');
  assert(socialSearchService.includes('STUDENT_SOURCE_LISTING_PATTERN'), 'source intake should recognize hostel and room vocabulary for student supply');
  assert(socialSearchService.includes("const listingType = studentListing ? 'students' : originalListingType"), 'student supply should store student-like source posts under the student category');
  assert(staffRoutes.includes("reason: 'non_uganda_location'"), 'staff bulk review should hold non-Uganda or foreign-token rows');
  assert(staffRoutes.includes("reason: 'not_a_listing'"), 'staff bulk review should hold clickbait/explainer source videos');
  assert(staffRoutes.includes('applyStaffBulkInternalDuplicateGate'), 'staff bulk review should deduplicate approvals inside the same run');
  assert(staffRoutes.includes("reason: 'internal_duplicate'"), 'staff bulk review should hold duplicate approvals inside the same run');
  assert(staffRoutes.includes('bulk_gate_preview'), 'staff listing preview should expose the same bulk-review gate decision');
  assert(staffRoutes.includes("reason: 'misclassified_sale'"), 'staff bulk review should hold suspicious sub-20M sale rows');
  assert(staffRoutes.includes('manual_notification_only'), 'staff bulk approval should record that owner WhatsApp is not auto-sent');
  assert(staffRoutes.includes('staffTikTokOembedOnlyBatch'), 'staff import API should force oEmbed for TikTok-only exact video batches');
  assert(staffRoutes.includes('metadata_tiktok_oembed_enabled'), 'staff import API should report TikTok oEmbed metadata mode');
  assert(app.includes('metadata_skipped_for_large_batch'), 'staff source import should explain when metadata was skipped for speed');
  assert(app.includes('setStaffTrainingTab'), 'staff training should render one focused workflow at a time');
  assert(app.includes('copyStaffTrainingScript'), 'staff scripts should be copyable');
  assert(app.includes('/api/staff/properties/${encodeURIComponent(propertyId)}/preview'), 'frontend should open staff listing preview before approval');
  assert(app.includes('adminReviewListingEditPanel(preview)'), 'staff preview should reuse the King review edit panel');
  assert(app.includes('collectAdminReviewListingPatch()'), 'staff preview save should collect the King review edit panel fields');
  assert(app.includes('initAdminReviewLocationMap(preview)'), 'staff preview should render the same King review map pin control');
  assert(app.includes('const location = preview.location_review || {}'), 'staff preview should define location guardrail data before rendering warnings');
  assert(app.includes('openStaffOwnerStatusWhatsApp'), 'staff decisions should open owner WhatsApp notification drafts');
  assert(app.includes('function staffBuildReviewWarningOverrides'), 'staff approval should build moderator warning overrides from preview checks');
  assert(staffApproveBody, 'staff approval handler should be present for targeted freeze checks');
  assert(app.includes('data-staff-approve-id='), 'staff approval button should use delegated click dispatch');
  assert(app.includes('ensureStaffModerationActionDelegates'), 'staff moderation should install delegated action handlers');
  assert(app.includes('staffApprovalDiagnostic("requesting"'), 'staff approval should expose a diagnostic before the status request');
  assert(app.includes('window.__makaugLastStaffApproval'), 'staff approval diagnostics should be readable by browser operators');
  assert(app.includes('function cleanText(value = "")'), 'staff approval helpers should define cleanText before decision buttons use it');
  assert(app.includes('function staffPreviewDecisionButtons()'), 'staff approval should keep the preview decision button helper');
  assert(staffApproveBody.includes('const statusPath = `/api/properties/${encodeURIComponent(propertyIdForRequest)}/status`;'), 'staff approval should build an explicit status path before request');
  assert(staffApproveBody.includes('staffSafeReviewPatch()'), 'staff approval should use a safe review patch fallback');
  assert(staffApproveBody.includes('listing: staffListingPreviewPatch()'), 'staff approval should persist preview listing edits in the status write');
  assert(staffApproveBody.includes('staffSafeReviewWarningOverrides(adminActiveReview)'), 'staff approval should use safe warning override fallback');
  assert(staffApproveBody.includes('staffSafeFoundOnlineApproval(adminActiveReview)'), 'staff approval should use safe found-online detection');
  assert(!staffApproveBody.includes('window.confirm('), 'staff approval should not use a blocking native confirm dialog');
  assert(!staffApproveBody.includes('saveStaffListingPreview(propertyId'), 'staff approval should not run the preview-save path before publishing');
  assert(staffApproveBody.includes('await new Promise((resolve) => window.setTimeout(resolve, 0));'), 'staff approval should yield once after setting busy state before the status write');
  assert(app.includes('STAFF_MODERATION_WRITE_TIMEOUT_MS'), 'staff moderation writes should have a timeout guard');
  assert(staffApproveBody.includes('staffApiRequestWithTimeout(statusPath'), 'staff status writes should use the bounded request helper');
  assert(app.includes('queueStaffDashboardRefreshAfterModeration({ refreshPublicSummary: true })'), 'staff approval should defer dashboard refresh after the write');
  assert(app.includes('async function refreshPublicOpportunitySummary'), 'staff approval refresh should not throw a missing public summary helper');
  assert(app.includes('Add a rejection reason in the Decision reason box first.'), 'staff rejection should require the visible decision reason');
  assert(app.includes('Add a Decision reason in the review panel before rejecting.'), 'queue-card rejection should open the review panel instead of prompting');
  assert(!app.includes('window.prompt("Why is this listing being rejected?"'), 'staff rejection should not use a blocking native prompt');
  assert(app.includes('warning_overrides: warningOverrides'), 'staff approval status call should submit warning overrides to the live publish API');
  assert(staffApproveBody.includes('const foundOnlineApproval = staffSafeFoundOnlineApproval(adminActiveReview)'), 'staff approval should detect found-online rows before publishing');
  assert(app.includes('staff_source_reviewed: true'), 'staff found-online approval should confirm source review to the backend');
  assert(app.includes('buildAdminApprovalWhatsAppMessage(listing)'), 'staff approval WhatsApp modal should have the same approval-message fallback as King moderation');
  assert(app.includes('Approve live after preview'), 'frontend should require preview before live approval');
  assert(app.includes('/api/staff/source-intake/exact-social/import'), 'frontend should call staff source intake import');
  assert(app.includes('/api/staff/source-intake/social-sweep'), 'frontend should call staff source sweep');
  assert(staffRoutes.includes('const staffSourceIntakeJobs = new Map()'), 'staff source intake should keep bounded async job state');
  assert(staffRoutes.includes("router.get('/source-intake/jobs/:jobId'"), 'staff source intake should expose a status endpoint for background imports');
  assert(staffRoutes.includes('return res.status(202).json({ ok: true, data: publicStaffSourceIntakeJob(job) });'), 'staff source intake queue should return immediately for async jobs');
  assert(app.includes('STAFF_SOURCE_INTAKE_SUBMIT_TIMEOUT_MS = 15000'), 'staff source intake submit should allow Render cold starts while still staying async');
  assert(app.includes('payload.async_job = true'), 'staff source queue action should request a background import job');
  assert(app.includes('scheduleStaffSourceJobPoll(data.job_id'), 'staff source queue action should poll the background job');
  assert(staffRoutes.includes('function logStaffActivityInBackground'), 'staff source sweep accept path should not block on audit logging');
  assert(staffRoutes.includes("logStaffActivityInBackground(req, 'staff_social_sweep_job_accepted'"), 'staff social sweep accepted audit should be backgrounded');
  assert(!staffRoutes.includes("await logStaffActivity(req, 'staff_social_sweep_job_accepted'"), 'staff social sweep should return the job id before audit logging');
  assert(app.includes('function canUseStaffSourceIntakeApi'), 'moderators should be recognized for staff source sweep triggers');
  assert(app.includes('function adminRunStaffSocialSweepFallback'), 'admin sweep controls should fall back to the staff async queue for moderators');
  assert(app.includes('return adminRunStaffSocialSweepFallback(normalized, studentFocus)'), 'moderator sweep clicks should not require ADMIN_API_KEY');
  const staffQueueSourceImportBody = app.slice(app.indexOf('async function staffQueueSourceImport'), app.indexOf('async function staffRunSourceSweep'));
  assert(!staffQueueSourceImportBody.includes('window.confirm('), 'staff source queue action should not use a blocking native confirm');
  assert(!staffQueueSourceImportBody.includes('await renderStaffDashboard()'), 'staff source queue action should not refresh heavy dashboard panels on the click path');
  assert(staffRoutes.includes('STAFF_SOCIAL_SWEEP_SOURCE_LIMIT'), 'staff social sweep should have a configurable high-volume source cap');
  assert(staffRoutes.includes("process.env.STAFF_SOCIAL_SWEEP_SOURCE_LIMIT || '50'"), 'staff social sweep should default to fast 50-source batches');
  assert(staffRoutes.includes('const STAFF_SOCIAL_SWEEP_PAGE_LIMIT = 1'), 'staff social sweep should only fetch one page per source');
  assert(staffRoutes.includes('STAFF_SOCIAL_SWEEP_TIME_BUDGET_MS'), 'staff social sweep should have a hard runtime budget');
  assert(staffRoutes.includes("process.env.STAFF_SOCIAL_SWEEP_TIME_BUDGET_MS || '45000'"), 'staff social sweep should cap live jobs at a 45s budget');
  assert(staffRoutes.includes("youtubeJobMode || 'channel_uploads'"), 'staff social sweep should default to high-yield YouTube channel uploads');
  assert(staffRoutes.includes("type: 'social_sweep'"), 'staff social sweep should return background jobs for live runs');
  assert(app.includes('STAFF_SOURCE_SWEEP_BATCH_SIZE = 50'), 'staff social sweep should run a meaningful 50-source batch');
  assert(app.includes('STAFF_SOURCE_DEEP_SWEEP_MAX_PAGES = 1'), 'staff dashboard should keep the deeper agency-channel profile time-bounded');
  assert(app.includes('STAFF_SOURCE_SEARCH_SWEEP_BATCH_SIZE = 20'), 'staff dashboard should keep broad YouTube search bounded to protect quota');
  assert(app.includes('function staffSourceSweepProfile'), 'staff source sweeps should use explicit agency/deep/search profiles');
  assert(app.includes('async_job: !dryRun'), 'staff social sweep should use async jobs for live runs');
  assert(app.includes('staffStoreSweepOffset(sourceOffset + requestedSourceCount, sweepProfile.key)'), 'staff social sweep should advance source batches separately by profile');
  assert(app.includes('if (!data.already_running) staffStoreSweepOffset(sourceOffset + requestedSourceCount, sweepProfile.key)'), 'staff social sweep should not advance the cursor when an existing job is reused');
  assert(app.includes('if (!data.already_running) staffStoreSweepOffset(sourceOffset + profile.maxSources, profile.offsetKey)'), 'admin-to-staff sweep fallback should not advance the cursor when an existing job is reused');
  assert(html.includes('staff-high-volume-source-sweep-20260707'), 'frontend cache version must be bumped for the high-volume staff source sweep');
  assert(html.includes('staff-source-deep-search-20260707'), 'frontend cache version must be bumped for deep/search source sweep controls');
  assert(server.includes('staff-source-sweep-async-unblock-20260709'), 'server should cache-bust the staff sweep async unblock');
  assert(html.includes('staff-source-sweep-async-unblock-20260709'), 'frontend cache version must be bumped for staff sweep async unblock');
  assert(html.includes('Deep agency sweep'), 'staff source intake should offer a deeper agency upload pass');
  assert(html.includes('Broad hashtag/search sweep'), 'staff source intake should offer a bounded broad discovery pass');
  assert(app.includes('non-listing construction/design/tutorial rows are hidden from active review'), 'staff dashboard should explain source-quality filtered rows');
  assert(app.includes('Copy CSV'), 'staff AI should render contact CSV copy control');
  assert(app.includes('function preferredAudienceForResolvedUser'), 'generic account drawer sign-in should resolve staff role from returned user');
  assert(app.includes('return derivePortalMode(user, "")'), 'finder drawer sign-in must not force moderator accounts into finder dashboard');
  assert(app.includes('const isModerator = accountAccessDrawerAudience === "moderator"'), 'staff sign-in drawer should treat moderator as an internal role');
  assert(app.includes('Sign in with your staff moderator account'), 'staff sign-in drawer should explain moderator access');
  assert(app.includes('staffModerateListing'), 'frontend should expose moderation action');
  assert(app.includes('moderator email or +256'), 'staff sign-in copy should be present');
  assert(staffRoutes.includes('STAFF_SOURCE_PRESETS'), 'staff API should return local source-search presets');
  assert(staffRoutes.includes('whatsapp_web_bridge_clients'), 'staff API should include hosted WhatsApp bridge heartbeat proof');
  assert(staffRoutes.includes('STAFF_REMOVED_STATUSES'), 'staff API should hide rejected/deleted/test rows from staff queues');
  assert(staffRoutes.includes('publicCustomerVisiblePropertyWhere'), 'staff live counts should use the same customer-visible suppression as public property APIs');
  assert(staffRoutes.includes('PUBLIC_SUPPRESSED_LISTING_MARKERS'), 'staff live counts should suppress soft-launch and QA records');
  assert(staffRoutes.includes("COUNT(*) FILTER (WHERE ${publicCustomerVisiblePropertyWhere('p')})::int AS live"), 'staff live property count must not include public-suppressed records');
  assert(staffRoutes.includes('source_presets: STAFF_SOURCE_PRESETS'), 'staff dashboard payload should include source presets');
  assert(staffRoutes.includes('monitor: staffSourceMonitorGuide()'), 'staff dashboard payload should include continuous source monitor guidance');
  assert(staffRoutes.includes('PROPERTY_SOURCE_REGISTRY_TARGET_COUNT'), 'staff source monitor guide should show the 60,000 source target');
  assert(staffRoutes.includes('continuous_social_monitor_run'), 'staff source monitor guide should expose the audit action for confirmed runs');
  assert(staffRoutes.includes('youtubeJobMode'), 'staff social sweep endpoint should pass through the YouTube job mode');
  assert(staffRoutes.includes("whatsapp: { ...whatsappSummary, bridge: whatsappBridge }"), 'staff dashboard payload should expose WhatsApp bridge status');
  assert(staffRoutes.includes('FROM whatsapp_messages m'), 'staff dashboard and assistant should fall back to raw WhatsApp messages');
  assert(staffRoutes.includes('warning_overrides: safeJsonObject(req.body.warning_overrides, {})'), 'staff review save API should accept moderator warning overrides');
  assert(staffRoutes.includes('extraPatch.review_warning_overrides = warningOverrides'), 'staff review save should persist warning overrides for the live publish route');
  assert(staffRoutes.includes('staff_review_warning_overrides_by'), 'staff review save should audit who recorded warning overrides');
  assert(staffRoutes.includes('checklist_items: automatedReview.checks'), 'staff preview should expose automated warning rows for moderator override keys');

  console.log('staff-moderator-workbench tests passed');
}

run();
