'use strict';

const HOW_TO_VIDEO_SLOTS = [
  {
    key: 'what-is-makaug',
    title: 'What is MakaUg?',
    description: 'A one-minute introduction to the Uganda-first property platform.',
    audience: 'all',
    category: 'about',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'Explore MakaUg',
    ctaUrl: '/about',
    status: 'slot_ready',
    sortOrder: 1
  },
  {
    key: 'search-property',
    title: 'How to search for property',
    description: 'Find homes, rentals, land, commercial spaces, and student rooms faster.',
    audience: 'property_seekers',
    category: 'search',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'Start searching',
    ctaUrl: '/for-sale',
    status: 'slot_ready',
    sortOrder: 2
  },
  {
    key: 'use-filters',
    title: 'How to use filters',
    description: 'Narrow results by area, price, type, beds, campus, and safety needs.',
    audience: 'property_seekers',
    category: 'search',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'Try filters',
    ctaUrl: '/to-rent',
    status: 'slot_ready',
    sortOrder: 3
  },
  {
    key: 'student-accommodation',
    title: 'How to find student accommodation',
    description: 'Search by campus, budget, room type, Wi-Fi, security, and move-in timing.',
    audience: 'students',
    category: 'student',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'Find student rooms',
    ctaUrl: '/student-accommodation',
    status: 'slot_ready',
    sortOrder: 4
  },
  {
    key: 'list-property',
    title: 'How to list property',
    description: 'Create a listing, add key details, verify contact information, and submit.',
    audience: 'owners',
    category: 'listing',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'List Property',
    ctaUrl: '/list-property',
    status: 'slot_ready',
    sortOrder: 5
  },
  {
    key: 'location-and-photos',
    title: 'How to add property location and photos',
    description: 'Use Find address or place, confirm the map pin, and upload useful photos.',
    audience: 'owners',
    category: 'listing',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'Open listing form',
    ctaUrl: '/list-property',
    status: 'slot_ready',
    sortOrder: 6
  },
  {
    key: 'whatsapp-contact',
    title: 'How to contact an owner or broker on WhatsApp',
    description: 'Send property context, reference, location, and your viewing question safely.',
    audience: 'all',
    category: 'whatsapp',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'Ask MakaUg',
    ctaUrl: 'https://wa.me/256760112587?text=Hello%20MakaUg,%20I%20need%20property%20help',
    status: 'slot_ready',
    sortOrder: 7
  },
  {
    key: 'save-searches-alerts',
    title: 'How to save searches and create alerts',
    description: 'Keep track of demand and get notified when matching listings appear.',
    audience: 'property_seekers',
    category: 'alerts',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'Save a search',
    ctaUrl: '/to-rent',
    status: 'slot_ready',
    sortOrder: 8
  },
  {
    key: 'book-viewing-callback',
    title: 'How to book a viewing or request callback',
    description: 'Understand viewing buttons, callback requests, and follow-up tracking.',
    audience: 'property_seekers',
    category: 'viewings',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'Find properties',
    ctaUrl: '/for-sale',
    status: 'slot_ready',
    sortOrder: 9
  },
  {
    key: 'stay-safe-report',
    title: 'How to stay safe and report suspicious listings',
    description: 'Learn red flags, title checks, payment safety, and fraud-report steps.',
    audience: 'all',
    category: 'safety',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'Read safety tips',
    ctaUrl: '/safety',
    status: 'slot_ready',
    sortOrder: 10
  },
  {
    key: 'ai-can-help',
    title: 'What MakaUg AI can help with',
    description: 'Search, list, create alerts, request help, and understand next steps.',
    audience: 'all',
    category: 'ai',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'Try AI',
    ctaUrl: '/discover-ai-chatbot',
    status: 'slot_ready',
    sortOrder: 11
  },
  {
    key: 'ai-search-whatsapp',
    title: 'How to search property using WhatsApp/AI',
    description: 'Ask naturally by area, budget, category, campus, or land need.',
    audience: 'all',
    category: 'ai',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'Open AI chatbot',
    ctaUrl: '/discover-ai-chatbot',
    status: 'slot_ready',
    sortOrder: 12
  },
  {
    key: 'ai-list-property',
    title: 'How to list property with AI help',
    description: 'Use the guided online form or WhatsApp listing path with safe prompts.',
    audience: 'owners',
    category: 'ai',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'List Property',
    ctaUrl: '/list-property',
    status: 'slot_ready',
    sortOrder: 13
  },
  {
    key: 'ai-alerts-recommendations',
    title: 'How to create alerts and recommendations',
    description: 'Turn searches into alerts and recommendation signals for better follow-up.',
    audience: 'property_seekers',
    category: 'ai',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'Save a search',
    ctaUrl: '/to-rent',
    status: 'slot_ready',
    sortOrder: 14
  },
  {
    key: 'ai-fraud-handoff',
    title: 'How to report fraud or request human help',
    description: 'Escalate suspicious listings, payment pressure, or complex property questions.',
    audience: 'all',
    category: 'ai',
    language: 'en',
    youtubeUrl: '',
    youtubeVideoId: '',
    thumbnailUrl: '',
    durationSeconds: 60,
    ctaLabel: 'Report suspicious activity',
    ctaUrl: '/anti-fraud',
    status: 'slot_ready',
    sortOrder: 15
  }
];

module.exports = {
  HOW_TO_VIDEO_SLOTS
};
