'use strict';

const MARKETPLACE_VERIFIED_PRICE_UGX = 150000;
const MARKETPLACE_VERIFIED_BILLING_PERIOD = 'month';
const MARKETPLACE_POLISH_MARKER = 'marketplace-polish-20260719';
const MARKETPLACE_FINAL_TWEAKS_MARKER = 'marketplace-final-tweaks-20260719';

module.exports = {
  MARKETPLACE_FINAL_TWEAKS_MARKER,
  MARKETPLACE_POLISH_MARKER,
  MARKETPLACE_VERIFIED_BILLING_PERIOD,
  MARKETPLACE_VERIFIED_PRICE_UGX
};
