const DISTRICTS = [
  'Abim', 'Adjumani', 'Agago', 'Alebtong', 'Amolatar', 'Amudat', 'Amuria', 'Amuru', 'Apac', 'Arua', 'Arua City',
  'Budaka', 'Bududa', 'Bugiri', 'Bugweri', 'Buhweju', 'Buikwe', 'Bukedea', 'Bukomansimbi', 'Bukwo', 'Bulambuli',
  'Buliisa', 'Bundibugyo', 'Bunyangabu', 'Bushenyi', 'Busia', 'Butaleja', 'Butambala', 'Butebo', 'Buvuma', 'Buyende', 'Dokolo',
  'Fort Portal City', 'Gomba', 'Gulu', 'Gulu City', 'Hoima', 'Hoima City', 'Ibanda', 'Iganga', 'Isingiro', 'Jinja', 'Jinja City', 'Kaabong', 'Kabale', 'Kabarole',
  'Kaberamaido', 'Kagadi', 'Kakumiro', 'Kalaki', 'Kalangala', 'Kaliro', 'Kalungu', 'Kampala', 'Kamuli', 'Kamwenge',
  'Kanungu', 'Kapchorwa', 'Kapelebyong', 'Karenga', 'Kassanda', 'Kasese', 'Katakwi', 'Kayunga', 'Kazo', 'Kibaale',
  'Kiboga', 'Kibuku', 'Kikuube', 'Kiruhura', 'Kiryandongo', 'Kisoro', 'Kitagwenda', 'Kitgum', 'Koboko', 'Kole',
  'Kotido', 'Kumi', 'Kwania', 'Kween', 'Kyankwanzi', 'Kyegegwa', 'Kyenjojo', 'Kyotera', 'Lamwo', 'Lira', 'Lira City',
  'Luuka', 'Luwero', 'Lwengo', 'Lyantonde', 'Madi-Okollo', 'Manafwa', 'Maracha', 'Masaka', 'Masaka City', 'Masindi', 'Mayuge',
  'Mbale', 'Mbale City', 'Mbarara', 'Mbarara City', 'Mitooma', 'Mityana', 'Moroto', 'Moyo', 'Mpigi', 'Mubende', 'Mukono', 'Nabilatuk',
  'Nakapiripirit', 'Nakaseke', 'Nakasongola', 'Namayingo', 'Namisindwa', 'Namutumba', 'Napak', 'Nebbi', 'Ngora', 'Ntoroko',
  'Ntungamo', 'Nwoya', 'Obongi', 'Omoro', 'Otuke', 'Oyam', 'Pader', 'Pakwach', 'Pallisa', 'Rakai',
  'Rubanda', 'Rubirizi', 'Rukiga', 'Rukungiri', 'Rwampara', 'Sembabule', 'Serere', 'Sheema', 'Sironko', 'Soroti', 'Soroti City', 'Terego', 'Tororo',
  'Wakiso', 'Yumbe', 'Zombo'
];

const UNIVERSITIES = [
  'Makerere University',
  'Kyambogo University',
  'Mbarara University of Science and Technology (MUST)',
  'Gulu University',
  'Busitema University',
  'Muni University',
  'Soroti University',
  'Lira University',
  'Kabale University',
  'Mountains of the Moon University',
  'Islamic University in Uganda (IUIU)',
  'Uganda Christian University (UCU)',
  'Uganda Martyrs University (UMU)',
  'Kampala International University (KIU)',
  'Nkumba University',
  'Ndejje University',
  'Bishop Stuart University',
  'Bugema University',
  'Cavendish University Uganda',
  'Victoria University Uganda',
  'ISBAT University',
  'International University of East Africa (IUEA)',
  'Universal Technology and Management University (UTAMU)',
  'African Bible University',
  'Africa Renewal University',
  'All Saints University Lango',
  'Ankole Western University',
  'Kumi University',
  'Muteesa I Royal University',
  'Uganda Pentecostal University',
  'University of Kisubi',
  'King Ceasar University',
  'Great Lakes Regional University',
  'Metropolitan International University',
  'Clarke International University',
  'St. Lawrence University Uganda',
  'Livingstone International University',
  'TEAM University',
  'Ibanda University',
  'Kampala University',
  'African Rural University',
  'Aga Khan University (Uganda Campus)',
  'Makerere University Business School (MUBS)',
  'Uganda Management Institute (UMI)',
  'Nexus International University',
  'Uganda National Institute for Teacher Education (UNITE)',
  'Valley University of Science & Technology',
  'University of Saint Joseph Mbarara'
];

// Historical names, spelling variants and campus shorthand stay searchable,
// but never create duplicate SEO landing pages. UNIVERSITIES is the single
// canonical 48-entry catalogue used by public filters and SEO routes.
const UNIVERSITY_ALIASES = Object.freeze({
  'Makerere University': ['makerere', 'makerere university', 'muk', 'kikoni', 'wandegeya', 'mulago'],
  'Makerere University Business School (MUBS)': ['mubs', 'makerere university business school', 'nakawa campus', 'nakawa'],
  'Kyambogo University': ['kyambogo', 'kyambogo university', 'banda', 'ntinda'],
  'Uganda Christian University (UCU)': ['ucu', 'uganda christian university', 'bishop tucker', 'mukono campus', 'mukono town', 'mukono'],
  'Kampala International University (KIU)': ['kiu', 'kampala international university', 'kansanga', 'kabalagala'],
  'Nkumba University': ['nkumba', 'nkumba university', 'entebbe'],
  'Ndejje University': ['ndejje', 'ndejje university'],
  'Uganda Martyrs University (UMU)': ['umu', 'uganda martyrs university', 'nkozi'],
  'Mbarara University of Science and Technology (MUST)': ['must', 'mbarara university', 'mbarara university of science and technology', 'mbarara'],
  'Gulu University': ['gulu university', 'gulu'],
  'Kabale University': ['kabale university', 'kabale'],
  'Lira University': ['lira university', 'lira'],
  'Busitema University': ['busitema', 'busitema university'],
  'Soroti University': ['soroti university', 'soroti'],
  'Islamic University in Uganda (IUIU)': ['iuiu', 'islamic university in uganda', 'mbale campus'],
  'Clarke International University': ['international health sciences university'],
  'King Ceasar University': ['king caesar university', 'king ceasor university', 'st. augustine international university'],
  'Nexus International University': ['virtual university uganda', 'virtual university of uganda'],
  'Universal Technology and Management University (UTAMU)': ['uganda technology and management university', 'utamu'],
  'Livingstone International University': ['livingstone international university', 'livingstone university'],
  'TEAM University': ['team university'],
  'St. Lawrence University Uganda': ['st. lawrence university', 'saint lawrence university']
});

const LISTING_TYPES = ['sale', 'rent', 'land', 'commercial', 'student', 'students'];
const PROPERTY_STATUSES = ['draft', 'pending', 'approved', 'rejected', 'hidden', 'deleted', 'archived', 'sold'];

module.exports = {
  DISTRICTS,
  UNIVERSITIES,
  UNIVERSITY_ALIASES,
  LISTING_TYPES,
  PROPERTY_STATUSES
};
