#!/usr/bin/env node
'use strict';

// npm run build:js
//
// assets/makaug-app.js stays the one source file (tests and the ZA tenant read
// it). This script writes two minified bundles next to it, which index.html
// loads instead:
//
//   assets/build/makaug-app.min.js    every visitor
//   assets/build/makaug-admin.min.js  only pages that carry the staff/admin
//                                     shell (protected routes)
//
// How the split is decided. makaug-app.js is a classic script: its top-level
// functions are globals, so a second classic script can hold some of them and
// both see each other's functions and top-level let/const. The admin bundle
// takes the top-level FUNCTION declarations that public code can never reach:
//   1. seeds: functions named admin*/staff*/king*/harvest*/… (ADMIN_NAME);
//   2. public roots: every function named by top-level statements, by the
//      public HTML (index.html as each public route serves it), and by the other
//      public scripts and server-rendered HTML;
//   3. everything reachable from the roots without passing through a seed
//      stays public. A function counts as referenced when its name appears as
//      an identifier OR as a word inside a string/template (onclick="…").
// Variable declarations and top-level statements always stay public.
//
// A seed that public code does reach must be listed below: KEEP_PUBLIC (it is
// used synchronously, so it stays in the public bundle) or ASYNC_ENTRY_POINTS
// (async/fire-and-forget; the public bundle gets a stub that loads the admin
// bundle and then calls the real function). Any other case fails the build,
// so a new public→admin call needs a deliberate decision here.

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const acorn = require('acorn');
const walk = require('acorn-walk');
const esbuild = require('esbuild');

const ROOT = path.join(__dirname, '..');
const SOURCE = path.join(ROOT, 'assets', 'makaug-app.js');
const OUT_DIR = path.join(ROOT, 'assets', 'build');
const PUBLIC_OUT = path.join(OUT_DIR, 'makaug-app.min.js');
const ADMIN_OUT = path.join(OUT_DIR, 'makaug-admin.min.js');

const ADMIN_NAME = /^(admin|staff|king|harvest|sourceIntake|lpAdmin|moderat)|(Admin|Staff|King|Harvest|Moderation|SourceIntake)[A-Z]|(Admin|Staff|King)$/;

const KEEP_PUBLIC = new Set([
  'loadStoredAdminApiKey', 'normalizeModerationStatus', 'adminAuthHeaders', 'adminEscape', 'adminAttr',
  'adminRecordLooksLikeTest', 'adminListingIdArg', 'adminStatusBadge', 'pendingAdminControlAfterAuth',
  'adminControlForPath', 'isSignedInAdminUser', 'openHarvestSubmissionModal', 'closeHarvestSubmissionModal',
  'submitHarvestSourceLink', 'adminScrollTo', 'ensureStaffModerationActionDelegates', 'updateAdminAccessEntrypoints',
  'unlockAdminAccess', 'adminSocialCaptureHelperScript', 'adminSocialCaptureBookmarkletUrl',
  'adminSocialCaptureHelperPanelHtml', 'adminCopySocialCaptureBookmarklet', 'adminSocialQuickPastePanelHtml',
  'adminOpenSocialQuickPastePanel'
]);

const ASYNC_ENTRY_POINTS = new Set([
  'renderStaffDashboard', 'renderAdminDashboard', 'renderAdminSetupStatus', 'initAdminReviewLocationMap',
  'refreshMarketplaceModerationQueue', 'openAdminControl', 'staffApprovePreviewListing'
]);

const PUBLIC_TEXT_FILES = () => [
  'assets/off-plan.js', 'assets/short-term.js', 'assets/makaug-site-i18n.js', 'server.js',
  ...fs.readdirSync(path.join(ROOT, 'services')).filter((f) => f.endsWith('.js')).map((f) => `services/${f}`),
  ...fs.readdirSync(path.join(ROOT, 'routes')).filter((f) => f.endsWith('.js')).map((f) => `routes/${f}`)
];

const WORD = /[A-Za-z_$][A-Za-z0-9_$]*/g;

function sha1(text) {
  return crypto.createHash('sha1').update(text).digest('hex');
}

function sourceHash(source = fs.readFileSync(SOURCE, 'utf8')) {
  return sha1(source).slice(0, 16);
}

function bannerFor(hash, kind) {
  return `/* makaug ${kind} bundle. source-sha1:${hash}. Generated by npm run build:js from assets/makaug-app.js; do not edit. */\n`;
}

function publicHtmlTexts() {
  const { sanitizePublicHtml, knownPublicRouteList } = require(path.join(ROOT, 'services', 'publicHtmlSanitizer.js'));
  const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  const routes = new Set([...knownPublicRouteList(), '/property/x', '/agents/x', '/broker/x', '/hostels/x', '/pay/x', '/off-plan/x', '/short-term/x', '/to-rent/kampala-kampala']);
  return [...routes].map((route) => sanitizePublicHtml(html, { pathname: route }));
}

function analyse(source) {
  const ast = acorn.parse(source, { ecmaVersion: 'latest', sourceType: 'script' });
  // A name declared twice at top level (the later one wins at runtime) is
  // treated as one unit: every declaration of it goes to the same bundle, in
  // source order, so the same one still wins.
  const functions = new Map();
  for (const node of ast.body) {
    if (node.type === 'FunctionDeclaration') {
      if (!functions.has(node.id.name)) functions.set(node.id.name, []);
      functions.get(node.id.name).push(node);
    }
  }
  const names = new Set(functions.keys());
  const refsOf = (node) => {
    const out = new Set();
    walk.full(node, (n) => {
      if (n.type === 'Identifier' && names.has(n.name)) out.add(n.name);
      else if (n.type === 'Literal' && typeof n.value === 'string') {
        for (const w of n.value.match(WORD) || []) if (names.has(w)) out.add(w);
      } else if (n.type === 'TemplateElement') {
        for (const w of String(n.value.cooked ?? n.value.raw).match(WORD) || []) if (names.has(w)) out.add(w);
      }
    });
    return out;
  };

  const seeds = new Set([...names].filter((name) => ADMIN_NAME.test(name) && !KEEP_PUBLIC.has(name)));
  const roots = new Set();
  for (const node of ast.body) if (node.type !== 'FunctionDeclaration') for (const r of refsOf(node)) roots.add(r);
  const texts = [...publicHtmlTexts(), ...PUBLIC_TEXT_FILES().map((f) => fs.readFileSync(path.join(ROOT, f), 'utf8'))];
  for (const text of texts) for (const w of text.match(WORD) || []) if (names.has(w)) roots.add(w);

  const reachedSeeds = new Set([...roots].filter((r) => seeds.has(r)));
  const refs = new Map();
  const publicSet = new Set();
  const stack = [...roots].filter((r) => !seeds.has(r));
  while (stack.length) {
    const name = stack.pop();
    if (publicSet.has(name)) continue;
    publicSet.add(name);
    if (!refs.has(name)) refs.set(name, new Set(functions.get(name).flatMap((node) => [...refsOf(node)])));
    for (const r of refs.get(name)) {
      if (seeds.has(r)) reachedSeeds.add(r);
      else if (!publicSet.has(r)) stack.push(r);
    }
  }

  const unexpected = [...reachedSeeds].filter((name) => !ASYNC_ENTRY_POINTS.has(name));
  if (unexpected.length) {
    throw new Error(`build:js: public code reaches admin functions that are in neither KEEP_PUBLIC nor ASYNC_ENTRY_POINTS: ${unexpected.join(', ')}`);
  }
  const adminNames = [...names].filter((name) => !publicSet.has(name));
  return { ast, functions, adminNames: new Set(adminNames), stubs: [...reachedSeeds].sort() };
}

function stubBlock(stubs) {
  return `;(function () {
  // Admin functions the public bundle can call. On staff/admin pages the admin
  // bundle runs first and these stay unset; elsewhere a call loads it once.
  var names = ${JSON.stringify(stubs)};
  var loading = null;
  function loadAdminBundle() {
    if (loading) return loading;
    loading = new Promise(function (resolve, reject) {
      var s = document.createElement("script");
      s.src = "/assets/makaug-admin.js?v=" + encodeURIComponent(window.__makaugAppVersion || "");
      s.onload = resolve;
      s.onerror = function () { loading = null; reject(new Error("admin bundle failed to load")); };
      document.body.appendChild(s);
    });
    return loading;
  }
  window.__makaugLoadAdminBundle = loadAdminBundle;
  names.forEach(function (name) {
    if (typeof window[name] === "function") return;
    var stub = function () {
      var self = this, args = arguments;
      return loadAdminBundle().then(function () {
        if (window[name] === stub) throw new Error(name + " is missing from the admin bundle");
        return window[name].apply(self, args);
      });
    };
    window[name] = stub;
  });
})();
`;
}

async function minify(code) {
  // No format: esbuild keeps top-level names (they are the page's globals).
  const result = await esbuild.transform(code, { minify: true, legalComments: 'none' });
  return result.code;
}

async function build({ write = true } = {}) {
  const source = fs.readFileSync(SOURCE, 'utf8');
  const hash = sourceHash(source);
  const { ast, functions, adminNames, stubs } = analyse(source);

  let publicCode = '';
  let adminCode = '';
  let cursor = 0;
  for (const node of ast.body) {
    if (node.type === 'FunctionDeclaration' && adminNames.has(node.id.name)) {
      publicCode += source.slice(cursor, node.start);
      adminCode += `${source.slice(node.start, node.end)}\n`;
      cursor = node.end;
    }
  }
  publicCode += source.slice(cursor);
  publicCode = `${stubBlock(stubs)}\n${publicCode}`;

  const publicMin = bannerFor(hash, 'public') + await minify(publicCode);
  const adminMin = bannerFor(hash, 'admin') + await minify(adminCode);

  for (const name of stubs) {
    if (!new RegExp(`function ${name}\\(`).test(adminMin)) throw new Error(`build:js: ${name} lost its name in the admin bundle`);
  }
  if (write) {
    fs.mkdirSync(OUT_DIR, { recursive: true });
    fs.writeFileSync(PUBLIC_OUT, publicMin);
    fs.writeFileSync(ADMIN_OUT, adminMin);
  }
  return {
    hash,
    sourceBytes: Buffer.byteLength(source),
    publicBytes: Buffer.byteLength(publicMin),
    adminBytes: Buffer.byteLength(adminMin),
    adminFunctions: adminNames.size,
    totalFunctions: functions.size,
    stubs
  };
}

function builtSourceHash(file) {
  try {
    const head = fs.readFileSync(file, 'utf8').slice(0, 300);
    return (head.match(/source-sha1:([a-f0-9]+)/) || [])[1] || '';
  } catch (_error) {
    return '';
  }
}

module.exports = { build, analyse, sourceHash, builtSourceHash, PUBLIC_OUT, ADMIN_OUT, SOURCE, KEEP_PUBLIC, ASYNC_ENTRY_POINTS };

if (require.main === module) {
  build().then((summary) => {
    const kb = (n) => `${(n / 1024).toFixed(0)} KB`;
    console.log(`makaug-app.js ${kb(summary.sourceBytes)} → public ${kb(summary.publicBytes)} + admin ${kb(summary.adminBytes)} (${summary.adminFunctions}/${summary.totalFunctions} functions moved; ${summary.stubs.length} async stubs)`);
  }).catch((error) => {
    console.error(error.message || error);
    process.exit(1);
  });
}
